package mx.gob.shcp.dgtsi.sfu.proyectos.model;

import java.util.ArrayList;
import java.util.List;

public class AvanceFisicoMapaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public AvanceFisicoMapaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdAvanceFisicoMapaIsNull() {
            addCriterion("ID_AVANCE_FISICO_MAPA is null");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoMapaIsNotNull() {
            addCriterion("ID_AVANCE_FISICO_MAPA is not null");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoMapaEqualTo(Integer value) {
            addCriterion("ID_AVANCE_FISICO_MAPA =", value, "idAvanceFisicoMapa");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoMapaNotEqualTo(Integer value) {
            addCriterion("ID_AVANCE_FISICO_MAPA <>", value, "idAvanceFisicoMapa");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoMapaGreaterThan(Integer value) {
            addCriterion("ID_AVANCE_FISICO_MAPA >", value, "idAvanceFisicoMapa");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoMapaGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_AVANCE_FISICO_MAPA >=", value, "idAvanceFisicoMapa");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoMapaLessThan(Integer value) {
            addCriterion("ID_AVANCE_FISICO_MAPA <", value, "idAvanceFisicoMapa");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoMapaLessThanOrEqualTo(Integer value) {
            addCriterion("ID_AVANCE_FISICO_MAPA <=", value, "idAvanceFisicoMapa");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoMapaIn(List<Integer> values) {
            addCriterion("ID_AVANCE_FISICO_MAPA in", values, "idAvanceFisicoMapa");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoMapaNotIn(List<Integer> values) {
            addCriterion("ID_AVANCE_FISICO_MAPA not in", values, "idAvanceFisicoMapa");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoMapaBetween(Integer value1, Integer value2) {
            addCriterion("ID_AVANCE_FISICO_MAPA between", value1, value2, "idAvanceFisicoMapa");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoMapaNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_AVANCE_FISICO_MAPA not between", value1, value2, "idAvanceFisicoMapa");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceIsNull() {
            addCriterion("ID_MAPA_AVANCE is null");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceIsNotNull() {
            addCriterion("ID_MAPA_AVANCE is not null");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceEqualTo(Integer value) {
            addCriterion("ID_MAPA_AVANCE =", value, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceNotEqualTo(Integer value) {
            addCriterion("ID_MAPA_AVANCE <>", value, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceGreaterThan(Integer value) {
            addCriterion("ID_MAPA_AVANCE >", value, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_MAPA_AVANCE >=", value, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceLessThan(Integer value) {
            addCriterion("ID_MAPA_AVANCE <", value, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceLessThanOrEqualTo(Integer value) {
            addCriterion("ID_MAPA_AVANCE <=", value, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceIn(List<Integer> values) {
            addCriterion("ID_MAPA_AVANCE in", values, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceNotIn(List<Integer> values) {
            addCriterion("ID_MAPA_AVANCE not in", values, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceBetween(Integer value1, Integer value2) {
            addCriterion("ID_MAPA_AVANCE between", value1, value2, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_MAPA_AVANCE not between", value1, value2, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoIsNull() {
            addCriterion("ID_AVANCE_FISICO is null");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoIsNotNull() {
            addCriterion("ID_AVANCE_FISICO is not null");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoEqualTo(Integer value) {
            addCriterion("ID_AVANCE_FISICO =", value, "idAvanceFisico");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoNotEqualTo(Integer value) {
            addCriterion("ID_AVANCE_FISICO <>", value, "idAvanceFisico");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoGreaterThan(Integer value) {
            addCriterion("ID_AVANCE_FISICO >", value, "idAvanceFisico");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_AVANCE_FISICO >=", value, "idAvanceFisico");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoLessThan(Integer value) {
            addCriterion("ID_AVANCE_FISICO <", value, "idAvanceFisico");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoLessThanOrEqualTo(Integer value) {
            addCriterion("ID_AVANCE_FISICO <=", value, "idAvanceFisico");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoIn(List<Integer> values) {
            addCriterion("ID_AVANCE_FISICO in", values, "idAvanceFisico");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoNotIn(List<Integer> values) {
            addCriterion("ID_AVANCE_FISICO not in", values, "idAvanceFisico");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoBetween(Integer value1, Integer value2) {
            addCriterion("ID_AVANCE_FISICO between", value1, value2, "idAvanceFisico");
            return (Criteria) this;
        }

        public Criteria andIdAvanceFisicoNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_AVANCE_FISICO not between", value1, value2, "idAvanceFisico");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}