package mx.gob.shcp.dgtsi.sfu.proyectos.model;

public class AvanceFisicoMapa {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AVANCE_FISICO_MAPA.ID_AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idAvanceFisicoMapa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AVANCE_FISICO_MAPA.ID_MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idMapaAvance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AVANCE_FISICO_MAPA.ID_AVANCE_FISICO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idAvanceFisico;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AVANCE_FISICO_MAPA.ID_AVANCE_FISICO_MAPA
     *
     * @return the value of AVANCE_FISICO_MAPA.ID_AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdAvanceFisicoMapa() {
        return idAvanceFisicoMapa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AVANCE_FISICO_MAPA.ID_AVANCE_FISICO_MAPA
     *
     * @param idAvanceFisicoMapa the value for AVANCE_FISICO_MAPA.ID_AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdAvanceFisicoMapa(Integer idAvanceFisicoMapa) {
        this.idAvanceFisicoMapa = idAvanceFisicoMapa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AVANCE_FISICO_MAPA.ID_MAPA_AVANCE
     *
     * @return the value of AVANCE_FISICO_MAPA.ID_MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdMapaAvance() {
        return idMapaAvance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AVANCE_FISICO_MAPA.ID_MAPA_AVANCE
     *
     * @param idMapaAvance the value for AVANCE_FISICO_MAPA.ID_MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdMapaAvance(Integer idMapaAvance) {
        this.idMapaAvance = idMapaAvance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AVANCE_FISICO_MAPA.ID_AVANCE_FISICO
     *
     * @return the value of AVANCE_FISICO_MAPA.ID_AVANCE_FISICO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdAvanceFisico() {
        return idAvanceFisico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AVANCE_FISICO_MAPA.ID_AVANCE_FISICO
     *
     * @param idAvanceFisico the value for AVANCE_FISICO_MAPA.ID_AVANCE_FISICO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdAvanceFisico(Integer idAvanceFisico) {
        this.idAvanceFisico = idAvanceFisico;
    }
}