package mx.gob.shcp.dgtsi.sfu.proyectos.model;

import java.util.Date;

public class AvanceFisico {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AVANCE_FISICO.ID_AVANCE_FISICO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idAvanceFisico;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AVANCE_FISICO.PERIODO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private String periodo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AVANCE_FISICO.FECHA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Date fecha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AVANCE_FISICO.TIPO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private String tipoMapa;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AVANCE_FISICO.ID_AVANCE_FISICO
     *
     * @return the value of AVANCE_FISICO.ID_AVANCE_FISICO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdAvanceFisico() {
        return idAvanceFisico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AVANCE_FISICO.ID_AVANCE_FISICO
     *
     * @param idAvanceFisico the value for AVANCE_FISICO.ID_AVANCE_FISICO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdAvanceFisico(Integer idAvanceFisico) {
        this.idAvanceFisico = idAvanceFisico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AVANCE_FISICO.PERIODO
     *
     * @return the value of AVANCE_FISICO.PERIODO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getPeriodo() {
        return periodo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AVANCE_FISICO.PERIODO
     *
     * @param periodo the value for AVANCE_FISICO.PERIODO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setPeriodo(String periodo) {
        this.periodo = periodo == null ? null : periodo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AVANCE_FISICO.FECHA
     *
     * @return the value of AVANCE_FISICO.FECHA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AVANCE_FISICO.FECHA
     *
     * @param fecha the value for AVANCE_FISICO.FECHA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AVANCE_FISICO.TIPO_MAPA
     *
     * @return the value of AVANCE_FISICO.TIPO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getTipoMapa() {
        return tipoMapa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AVANCE_FISICO.TIPO_MAPA
     *
     * @param tipoMapa the value for AVANCE_FISICO.TIPO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setTipoMapa(String tipoMapa) {
        this.tipoMapa = tipoMapa == null ? null : tipoMapa.trim();
    }
}