package mx.gob.shcp.dgtsi.sfu.proyectos.model;

public class Beneficiario {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BENEFICIARIO.ID_BENEFICIARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idBeneficiario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BENEFICIARIO.HOMBRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer hombres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BENEFICIARIO.MUJERES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer mujeres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BENEFICIARIO.ID_PROYECTO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idProyecto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BENEFICIARIO.ID_BENEFICIARIO
     *
     * @return the value of BENEFICIARIO.ID_BENEFICIARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdBeneficiario() {
        return idBeneficiario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BENEFICIARIO.ID_BENEFICIARIO
     *
     * @param idBeneficiario the value for BENEFICIARIO.ID_BENEFICIARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdBeneficiario(Integer idBeneficiario) {
        this.idBeneficiario = idBeneficiario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BENEFICIARIO.HOMBRES
     *
     * @return the value of BENEFICIARIO.HOMBRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getHombres() {
        return hombres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BENEFICIARIO.HOMBRES
     *
     * @param hombres the value for BENEFICIARIO.HOMBRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setHombres(Integer hombres) {
        this.hombres = hombres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BENEFICIARIO.MUJERES
     *
     * @return the value of BENEFICIARIO.MUJERES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getMujeres() {
        return mujeres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BENEFICIARIO.MUJERES
     *
     * @param mujeres the value for BENEFICIARIO.MUJERES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setMujeres(Integer mujeres) {
        this.mujeres = mujeres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BENEFICIARIO.ID_PROYECTO
     *
     * @return the value of BENEFICIARIO.ID_PROYECTO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdProyecto() {
        return idProyecto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BENEFICIARIO.ID_PROYECTO
     *
     * @param idProyecto the value for BENEFICIARIO.ID_PROYECTO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdProyecto(Integer idProyecto) {
        this.idProyecto = idProyecto;
    }
}