package mx.gob.shcp.dgtsi.sfu.proyectos.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ContratoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public ContratoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdContratoIsNull() {
            addCriterion("ID_CONTRATO is null");
            return (Criteria) this;
        }

        public Criteria andIdContratoIsNotNull() {
            addCriterion("ID_CONTRATO is not null");
            return (Criteria) this;
        }

        public Criteria andIdContratoEqualTo(Integer value) {
            addCriterion("ID_CONTRATO =", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoNotEqualTo(Integer value) {
            addCriterion("ID_CONTRATO <>", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoGreaterThan(Integer value) {
            addCriterion("ID_CONTRATO >", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_CONTRATO >=", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoLessThan(Integer value) {
            addCriterion("ID_CONTRATO <", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoLessThanOrEqualTo(Integer value) {
            addCriterion("ID_CONTRATO <=", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoIn(List<Integer> values) {
            addCriterion("ID_CONTRATO in", values, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoNotIn(List<Integer> values) {
            addCriterion("ID_CONTRATO not in", values, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoBetween(Integer value1, Integer value2) {
            addCriterion("ID_CONTRATO between", value1, value2, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_CONTRATO not between", value1, value2, "idContrato");
            return (Criteria) this;
        }

        public Criteria andRfcConvocanteIsNull() {
            addCriterion("RFC_CONVOCANTE is null");
            return (Criteria) this;
        }

        public Criteria andRfcConvocanteIsNotNull() {
            addCriterion("RFC_CONVOCANTE is not null");
            return (Criteria) this;
        }

        public Criteria andRfcConvocanteEqualTo(String value) {
            addCriterion("RFC_CONVOCANTE =", value, "rfcConvocante");
            return (Criteria) this;
        }

        public Criteria andRfcConvocanteNotEqualTo(String value) {
            addCriterion("RFC_CONVOCANTE <>", value, "rfcConvocante");
            return (Criteria) this;
        }

        public Criteria andRfcConvocanteGreaterThan(String value) {
            addCriterion("RFC_CONVOCANTE >", value, "rfcConvocante");
            return (Criteria) this;
        }

        public Criteria andRfcConvocanteGreaterThanOrEqualTo(String value) {
            addCriterion("RFC_CONVOCANTE >=", value, "rfcConvocante");
            return (Criteria) this;
        }

        public Criteria andRfcConvocanteLessThan(String value) {
            addCriterion("RFC_CONVOCANTE <", value, "rfcConvocante");
            return (Criteria) this;
        }

        public Criteria andRfcConvocanteLessThanOrEqualTo(String value) {
            addCriterion("RFC_CONVOCANTE <=", value, "rfcConvocante");
            return (Criteria) this;
        }

        public Criteria andRfcConvocanteLike(String value) {
            addCriterion("RFC_CONVOCANTE like", value, "rfcConvocante");
            return (Criteria) this;
        }

        public Criteria andRfcConvocanteNotLike(String value) {
            addCriterion("RFC_CONVOCANTE not like", value, "rfcConvocante");
            return (Criteria) this;
        }

        public Criteria andRfcConvocanteIn(List<String> values) {
            addCriterion("RFC_CONVOCANTE in", values, "rfcConvocante");
            return (Criteria) this;
        }

        public Criteria andRfcConvocanteNotIn(List<String> values) {
            addCriterion("RFC_CONVOCANTE not in", values, "rfcConvocante");
            return (Criteria) this;
        }

        public Criteria andRfcConvocanteBetween(String value1, String value2) {
            addCriterion("RFC_CONVOCANTE between", value1, value2, "rfcConvocante");
            return (Criteria) this;
        }

        public Criteria andRfcConvocanteNotBetween(String value1, String value2) {
            addCriterion("RFC_CONVOCANTE not between", value1, value2, "rfcConvocante");
            return (Criteria) this;
        }

        public Criteria andRfcContratistaIsNull() {
            addCriterion("RFC_CONTRATISTA is null");
            return (Criteria) this;
        }

        public Criteria andRfcContratistaIsNotNull() {
            addCriterion("RFC_CONTRATISTA is not null");
            return (Criteria) this;
        }

        public Criteria andRfcContratistaEqualTo(String value) {
            addCriterion("RFC_CONTRATISTA =", value, "rfcContratista");
            return (Criteria) this;
        }

        public Criteria andRfcContratistaNotEqualTo(String value) {
            addCriterion("RFC_CONTRATISTA <>", value, "rfcContratista");
            return (Criteria) this;
        }

        public Criteria andRfcContratistaGreaterThan(String value) {
            addCriterion("RFC_CONTRATISTA >", value, "rfcContratista");
            return (Criteria) this;
        }

        public Criteria andRfcContratistaGreaterThanOrEqualTo(String value) {
            addCriterion("RFC_CONTRATISTA >=", value, "rfcContratista");
            return (Criteria) this;
        }

        public Criteria andRfcContratistaLessThan(String value) {
            addCriterion("RFC_CONTRATISTA <", value, "rfcContratista");
            return (Criteria) this;
        }

        public Criteria andRfcContratistaLessThanOrEqualTo(String value) {
            addCriterion("RFC_CONTRATISTA <=", value, "rfcContratista");
            return (Criteria) this;
        }

        public Criteria andRfcContratistaLike(String value) {
            addCriterion("RFC_CONTRATISTA like", value, "rfcContratista");
            return (Criteria) this;
        }

        public Criteria andRfcContratistaNotLike(String value) {
            addCriterion("RFC_CONTRATISTA not like", value, "rfcContratista");
            return (Criteria) this;
        }

        public Criteria andRfcContratistaIn(List<String> values) {
            addCriterion("RFC_CONTRATISTA in", values, "rfcContratista");
            return (Criteria) this;
        }

        public Criteria andRfcContratistaNotIn(List<String> values) {
            addCriterion("RFC_CONTRATISTA not in", values, "rfcContratista");
            return (Criteria) this;
        }

        public Criteria andRfcContratistaBetween(String value1, String value2) {
            addCriterion("RFC_CONTRATISTA between", value1, value2, "rfcContratista");
            return (Criteria) this;
        }

        public Criteria andRfcContratistaNotBetween(String value1, String value2) {
            addCriterion("RFC_CONTRATISTA not between", value1, value2, "rfcContratista");
            return (Criteria) this;
        }

        public Criteria andConvocanteIsNull() {
            addCriterion("CONVOCANTE is null");
            return (Criteria) this;
        }

        public Criteria andConvocanteIsNotNull() {
            addCriterion("CONVOCANTE is not null");
            return (Criteria) this;
        }

        public Criteria andConvocanteEqualTo(String value) {
            addCriterion("CONVOCANTE =", value, "convocante");
            return (Criteria) this;
        }

        public Criteria andConvocanteNotEqualTo(String value) {
            addCriterion("CONVOCANTE <>", value, "convocante");
            return (Criteria) this;
        }

        public Criteria andConvocanteGreaterThan(String value) {
            addCriterion("CONVOCANTE >", value, "convocante");
            return (Criteria) this;
        }

        public Criteria andConvocanteGreaterThanOrEqualTo(String value) {
            addCriterion("CONVOCANTE >=", value, "convocante");
            return (Criteria) this;
        }

        public Criteria andConvocanteLessThan(String value) {
            addCriterion("CONVOCANTE <", value, "convocante");
            return (Criteria) this;
        }

        public Criteria andConvocanteLessThanOrEqualTo(String value) {
            addCriterion("CONVOCANTE <=", value, "convocante");
            return (Criteria) this;
        }

        public Criteria andConvocanteLike(String value) {
            addCriterion("CONVOCANTE like", value, "convocante");
            return (Criteria) this;
        }

        public Criteria andConvocanteNotLike(String value) {
            addCriterion("CONVOCANTE not like", value, "convocante");
            return (Criteria) this;
        }

        public Criteria andConvocanteIn(List<String> values) {
            addCriterion("CONVOCANTE in", values, "convocante");
            return (Criteria) this;
        }

        public Criteria andConvocanteNotIn(List<String> values) {
            addCriterion("CONVOCANTE not in", values, "convocante");
            return (Criteria) this;
        }

        public Criteria andConvocanteBetween(String value1, String value2) {
            addCriterion("CONVOCANTE between", value1, value2, "convocante");
            return (Criteria) this;
        }

        public Criteria andConvocanteNotBetween(String value1, String value2) {
            addCriterion("CONVOCANTE not between", value1, value2, "convocante");
            return (Criteria) this;
        }

        public Criteria andContratistaIsNull() {
            addCriterion("CONTRATISTA is null");
            return (Criteria) this;
        }

        public Criteria andContratistaIsNotNull() {
            addCriterion("CONTRATISTA is not null");
            return (Criteria) this;
        }

        public Criteria andContratistaEqualTo(String value) {
            addCriterion("CONTRATISTA =", value, "contratista");
            return (Criteria) this;
        }

        public Criteria andContratistaNotEqualTo(String value) {
            addCriterion("CONTRATISTA <>", value, "contratista");
            return (Criteria) this;
        }

        public Criteria andContratistaGreaterThan(String value) {
            addCriterion("CONTRATISTA >", value, "contratista");
            return (Criteria) this;
        }

        public Criteria andContratistaGreaterThanOrEqualTo(String value) {
            addCriterion("CONTRATISTA >=", value, "contratista");
            return (Criteria) this;
        }

        public Criteria andContratistaLessThan(String value) {
            addCriterion("CONTRATISTA <", value, "contratista");
            return (Criteria) this;
        }

        public Criteria andContratistaLessThanOrEqualTo(String value) {
            addCriterion("CONTRATISTA <=", value, "contratista");
            return (Criteria) this;
        }

        public Criteria andContratistaLike(String value) {
            addCriterion("CONTRATISTA like", value, "contratista");
            return (Criteria) this;
        }

        public Criteria andContratistaNotLike(String value) {
            addCriterion("CONTRATISTA not like", value, "contratista");
            return (Criteria) this;
        }

        public Criteria andContratistaIn(List<String> values) {
            addCriterion("CONTRATISTA in", values, "contratista");
            return (Criteria) this;
        }

        public Criteria andContratistaNotIn(List<String> values) {
            addCriterion("CONTRATISTA not in", values, "contratista");
            return (Criteria) this;
        }

        public Criteria andContratistaBetween(String value1, String value2) {
            addCriterion("CONTRATISTA between", value1, value2, "contratista");
            return (Criteria) this;
        }

        public Criteria andContratistaNotBetween(String value1, String value2) {
            addCriterion("CONTRATISTA not between", value1, value2, "contratista");
            return (Criteria) this;
        }

        public Criteria andNumProcedimientoIsNull() {
            addCriterion("NUM_PROCEDIMIENTO is null");
            return (Criteria) this;
        }

        public Criteria andNumProcedimientoIsNotNull() {
            addCriterion("NUM_PROCEDIMIENTO is not null");
            return (Criteria) this;
        }

        public Criteria andNumProcedimientoEqualTo(String value) {
            addCriterion("NUM_PROCEDIMIENTO =", value, "numProcedimiento");
            return (Criteria) this;
        }

        public Criteria andNumProcedimientoNotEqualTo(String value) {
            addCriterion("NUM_PROCEDIMIENTO <>", value, "numProcedimiento");
            return (Criteria) this;
        }

        public Criteria andNumProcedimientoGreaterThan(String value) {
            addCriterion("NUM_PROCEDIMIENTO >", value, "numProcedimiento");
            return (Criteria) this;
        }

        public Criteria andNumProcedimientoGreaterThanOrEqualTo(String value) {
            addCriterion("NUM_PROCEDIMIENTO >=", value, "numProcedimiento");
            return (Criteria) this;
        }

        public Criteria andNumProcedimientoLessThan(String value) {
            addCriterion("NUM_PROCEDIMIENTO <", value, "numProcedimiento");
            return (Criteria) this;
        }

        public Criteria andNumProcedimientoLessThanOrEqualTo(String value) {
            addCriterion("NUM_PROCEDIMIENTO <=", value, "numProcedimiento");
            return (Criteria) this;
        }

        public Criteria andNumProcedimientoLike(String value) {
            addCriterion("NUM_PROCEDIMIENTO like", value, "numProcedimiento");
            return (Criteria) this;
        }

        public Criteria andNumProcedimientoNotLike(String value) {
            addCriterion("NUM_PROCEDIMIENTO not like", value, "numProcedimiento");
            return (Criteria) this;
        }

        public Criteria andNumProcedimientoIn(List<String> values) {
            addCriterion("NUM_PROCEDIMIENTO in", values, "numProcedimiento");
            return (Criteria) this;
        }

        public Criteria andNumProcedimientoNotIn(List<String> values) {
            addCriterion("NUM_PROCEDIMIENTO not in", values, "numProcedimiento");
            return (Criteria) this;
        }

        public Criteria andNumProcedimientoBetween(String value1, String value2) {
            addCriterion("NUM_PROCEDIMIENTO between", value1, value2, "numProcedimiento");
            return (Criteria) this;
        }

        public Criteria andNumProcedimientoNotBetween(String value1, String value2) {
            addCriterion("NUM_PROCEDIMIENTO not between", value1, value2, "numProcedimiento");
            return (Criteria) this;
        }

        public Criteria andTipoProcedimientoIsNull() {
            addCriterion("TIPO_PROCEDIMIENTO is null");
            return (Criteria) this;
        }

        public Criteria andTipoProcedimientoIsNotNull() {
            addCriterion("TIPO_PROCEDIMIENTO is not null");
            return (Criteria) this;
        }

        public Criteria andTipoProcedimientoEqualTo(String value) {
            addCriterion("TIPO_PROCEDIMIENTO =", value, "tipoProcedimiento");
            return (Criteria) this;
        }

        public Criteria andTipoProcedimientoNotEqualTo(String value) {
            addCriterion("TIPO_PROCEDIMIENTO <>", value, "tipoProcedimiento");
            return (Criteria) this;
        }

        public Criteria andTipoProcedimientoGreaterThan(String value) {
            addCriterion("TIPO_PROCEDIMIENTO >", value, "tipoProcedimiento");
            return (Criteria) this;
        }

        public Criteria andTipoProcedimientoGreaterThanOrEqualTo(String value) {
            addCriterion("TIPO_PROCEDIMIENTO >=", value, "tipoProcedimiento");
            return (Criteria) this;
        }

        public Criteria andTipoProcedimientoLessThan(String value) {
            addCriterion("TIPO_PROCEDIMIENTO <", value, "tipoProcedimiento");
            return (Criteria) this;
        }

        public Criteria andTipoProcedimientoLessThanOrEqualTo(String value) {
            addCriterion("TIPO_PROCEDIMIENTO <=", value, "tipoProcedimiento");
            return (Criteria) this;
        }

        public Criteria andTipoProcedimientoLike(String value) {
            addCriterion("TIPO_PROCEDIMIENTO like", value, "tipoProcedimiento");
            return (Criteria) this;
        }

        public Criteria andTipoProcedimientoNotLike(String value) {
            addCriterion("TIPO_PROCEDIMIENTO not like", value, "tipoProcedimiento");
            return (Criteria) this;
        }

        public Criteria andTipoProcedimientoIn(List<String> values) {
            addCriterion("TIPO_PROCEDIMIENTO in", values, "tipoProcedimiento");
            return (Criteria) this;
        }

        public Criteria andTipoProcedimientoNotIn(List<String> values) {
            addCriterion("TIPO_PROCEDIMIENTO not in", values, "tipoProcedimiento");
            return (Criteria) this;
        }

        public Criteria andTipoProcedimientoBetween(String value1, String value2) {
            addCriterion("TIPO_PROCEDIMIENTO between", value1, value2, "tipoProcedimiento");
            return (Criteria) this;
        }

        public Criteria andTipoProcedimientoNotBetween(String value1, String value2) {
            addCriterion("TIPO_PROCEDIMIENTO not between", value1, value2, "tipoProcedimiento");
            return (Criteria) this;
        }

        public Criteria andTipoContratacionIsNull() {
            addCriterion("TIPO_CONTRATACION is null");
            return (Criteria) this;
        }

        public Criteria andTipoContratacionIsNotNull() {
            addCriterion("TIPO_CONTRATACION is not null");
            return (Criteria) this;
        }

        public Criteria andTipoContratacionEqualTo(String value) {
            addCriterion("TIPO_CONTRATACION =", value, "tipoContratacion");
            return (Criteria) this;
        }

        public Criteria andTipoContratacionNotEqualTo(String value) {
            addCriterion("TIPO_CONTRATACION <>", value, "tipoContratacion");
            return (Criteria) this;
        }

        public Criteria andTipoContratacionGreaterThan(String value) {
            addCriterion("TIPO_CONTRATACION >", value, "tipoContratacion");
            return (Criteria) this;
        }

        public Criteria andTipoContratacionGreaterThanOrEqualTo(String value) {
            addCriterion("TIPO_CONTRATACION >=", value, "tipoContratacion");
            return (Criteria) this;
        }

        public Criteria andTipoContratacionLessThan(String value) {
            addCriterion("TIPO_CONTRATACION <", value, "tipoContratacion");
            return (Criteria) this;
        }

        public Criteria andTipoContratacionLessThanOrEqualTo(String value) {
            addCriterion("TIPO_CONTRATACION <=", value, "tipoContratacion");
            return (Criteria) this;
        }

        public Criteria andTipoContratacionLike(String value) {
            addCriterion("TIPO_CONTRATACION like", value, "tipoContratacion");
            return (Criteria) this;
        }

        public Criteria andTipoContratacionNotLike(String value) {
            addCriterion("TIPO_CONTRATACION not like", value, "tipoContratacion");
            return (Criteria) this;
        }

        public Criteria andTipoContratacionIn(List<String> values) {
            addCriterion("TIPO_CONTRATACION in", values, "tipoContratacion");
            return (Criteria) this;
        }

        public Criteria andTipoContratacionNotIn(List<String> values) {
            addCriterion("TIPO_CONTRATACION not in", values, "tipoContratacion");
            return (Criteria) this;
        }

        public Criteria andTipoContratacionBetween(String value1, String value2) {
            addCriterion("TIPO_CONTRATACION between", value1, value2, "tipoContratacion");
            return (Criteria) this;
        }

        public Criteria andTipoContratacionNotBetween(String value1, String value2) {
            addCriterion("TIPO_CONTRATACION not between", value1, value2, "tipoContratacion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("DESCRIPCION is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("DESCRIPCION is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("DESCRIPCION =", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("DESCRIPCION <>", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("DESCRIPCION >", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION >=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("DESCRIPCION <", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION <=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("DESCRIPCION like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("DESCRIPCION not like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("DESCRIPCION in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("DESCRIPCION not in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("DESCRIPCION between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPCION not between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andVinculoIsNull() {
            addCriterion("VINCULO is null");
            return (Criteria) this;
        }

        public Criteria andVinculoIsNotNull() {
            addCriterion("VINCULO is not null");
            return (Criteria) this;
        }

        public Criteria andVinculoEqualTo(String value) {
            addCriterion("VINCULO =", value, "vinculo");
            return (Criteria) this;
        }

        public Criteria andVinculoNotEqualTo(String value) {
            addCriterion("VINCULO <>", value, "vinculo");
            return (Criteria) this;
        }

        public Criteria andVinculoGreaterThan(String value) {
            addCriterion("VINCULO >", value, "vinculo");
            return (Criteria) this;
        }

        public Criteria andVinculoGreaterThanOrEqualTo(String value) {
            addCriterion("VINCULO >=", value, "vinculo");
            return (Criteria) this;
        }

        public Criteria andVinculoLessThan(String value) {
            addCriterion("VINCULO <", value, "vinculo");
            return (Criteria) this;
        }

        public Criteria andVinculoLessThanOrEqualTo(String value) {
            addCriterion("VINCULO <=", value, "vinculo");
            return (Criteria) this;
        }

        public Criteria andVinculoLike(String value) {
            addCriterion("VINCULO like", value, "vinculo");
            return (Criteria) this;
        }

        public Criteria andVinculoNotLike(String value) {
            addCriterion("VINCULO not like", value, "vinculo");
            return (Criteria) this;
        }

        public Criteria andVinculoIn(List<String> values) {
            addCriterion("VINCULO in", values, "vinculo");
            return (Criteria) this;
        }

        public Criteria andVinculoNotIn(List<String> values) {
            addCriterion("VINCULO not in", values, "vinculo");
            return (Criteria) this;
        }

        public Criteria andVinculoBetween(String value1, String value2) {
            addCriterion("VINCULO between", value1, value2, "vinculo");
            return (Criteria) this;
        }

        public Criteria andVinculoNotBetween(String value1, String value2) {
            addCriterion("VINCULO not between", value1, value2, "vinculo");
            return (Criteria) this;
        }

        public Criteria andFechaConclusionIsNull() {
            addCriterion("FECHA_CONCLUSION is null");
            return (Criteria) this;
        }

        public Criteria andFechaConclusionIsNotNull() {
            addCriterion("FECHA_CONCLUSION is not null");
            return (Criteria) this;
        }

        public Criteria andFechaConclusionEqualTo(Date value) {
            addCriterionForJDBCDate("FECHA_CONCLUSION =", value, "fechaConclusion");
            return (Criteria) this;
        }

        public Criteria andFechaConclusionNotEqualTo(Date value) {
            addCriterionForJDBCDate("FECHA_CONCLUSION <>", value, "fechaConclusion");
            return (Criteria) this;
        }

        public Criteria andFechaConclusionGreaterThan(Date value) {
            addCriterionForJDBCDate("FECHA_CONCLUSION >", value, "fechaConclusion");
            return (Criteria) this;
        }

        public Criteria andFechaConclusionGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FECHA_CONCLUSION >=", value, "fechaConclusion");
            return (Criteria) this;
        }

        public Criteria andFechaConclusionLessThan(Date value) {
            addCriterionForJDBCDate("FECHA_CONCLUSION <", value, "fechaConclusion");
            return (Criteria) this;
        }

        public Criteria andFechaConclusionLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FECHA_CONCLUSION <=", value, "fechaConclusion");
            return (Criteria) this;
        }

        public Criteria andFechaConclusionIn(List<Date> values) {
            addCriterionForJDBCDate("FECHA_CONCLUSION in", values, "fechaConclusion");
            return (Criteria) this;
        }

        public Criteria andFechaConclusionNotIn(List<Date> values) {
            addCriterionForJDBCDate("FECHA_CONCLUSION not in", values, "fechaConclusion");
            return (Criteria) this;
        }

        public Criteria andFechaConclusionBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FECHA_CONCLUSION between", value1, value2, "fechaConclusion");
            return (Criteria) this;
        }

        public Criteria andFechaConclusionNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FECHA_CONCLUSION not between", value1, value2, "fechaConclusion");
            return (Criteria) this;
        }

        public Criteria andVinculoTerminoIsNull() {
            addCriterion("VINCULO_TERMINO is null");
            return (Criteria) this;
        }

        public Criteria andVinculoTerminoIsNotNull() {
            addCriterion("VINCULO_TERMINO is not null");
            return (Criteria) this;
        }

        public Criteria andVinculoTerminoEqualTo(String value) {
            addCriterion("VINCULO_TERMINO =", value, "vinculoTermino");
            return (Criteria) this;
        }

        public Criteria andVinculoTerminoNotEqualTo(String value) {
            addCriterion("VINCULO_TERMINO <>", value, "vinculoTermino");
            return (Criteria) this;
        }

        public Criteria andVinculoTerminoGreaterThan(String value) {
            addCriterion("VINCULO_TERMINO >", value, "vinculoTermino");
            return (Criteria) this;
        }

        public Criteria andVinculoTerminoGreaterThanOrEqualTo(String value) {
            addCriterion("VINCULO_TERMINO >=", value, "vinculoTermino");
            return (Criteria) this;
        }

        public Criteria andVinculoTerminoLessThan(String value) {
            addCriterion("VINCULO_TERMINO <", value, "vinculoTermino");
            return (Criteria) this;
        }

        public Criteria andVinculoTerminoLessThanOrEqualTo(String value) {
            addCriterion("VINCULO_TERMINO <=", value, "vinculoTermino");
            return (Criteria) this;
        }

        public Criteria andVinculoTerminoLike(String value) {
            addCriterion("VINCULO_TERMINO like", value, "vinculoTermino");
            return (Criteria) this;
        }

        public Criteria andVinculoTerminoNotLike(String value) {
            addCriterion("VINCULO_TERMINO not like", value, "vinculoTermino");
            return (Criteria) this;
        }

        public Criteria andVinculoTerminoIn(List<String> values) {
            addCriterion("VINCULO_TERMINO in", values, "vinculoTermino");
            return (Criteria) this;
        }

        public Criteria andVinculoTerminoNotIn(List<String> values) {
            addCriterion("VINCULO_TERMINO not in", values, "vinculoTermino");
            return (Criteria) this;
        }

        public Criteria andVinculoTerminoBetween(String value1, String value2) {
            addCriterion("VINCULO_TERMINO between", value1, value2, "vinculoTermino");
            return (Criteria) this;
        }

        public Criteria andVinculoTerminoNotBetween(String value1, String value2) {
            addCriterion("VINCULO_TERMINO not between", value1, value2, "vinculoTermino");
            return (Criteria) this;
        }

        public Criteria andMontoIsNull() {
            addCriterion("MONTO is null");
            return (Criteria) this;
        }

        public Criteria andMontoIsNotNull() {
            addCriterion("MONTO is not null");
            return (Criteria) this;
        }

        public Criteria andMontoEqualTo(BigDecimal value) {
            addCriterion("MONTO =", value, "monto");
            return (Criteria) this;
        }

        public Criteria andMontoNotEqualTo(BigDecimal value) {
            addCriterion("MONTO <>", value, "monto");
            return (Criteria) this;
        }

        public Criteria andMontoGreaterThan(BigDecimal value) {
            addCriterion("MONTO >", value, "monto");
            return (Criteria) this;
        }

        public Criteria andMontoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MONTO >=", value, "monto");
            return (Criteria) this;
        }

        public Criteria andMontoLessThan(BigDecimal value) {
            addCriterion("MONTO <", value, "monto");
            return (Criteria) this;
        }

        public Criteria andMontoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MONTO <=", value, "monto");
            return (Criteria) this;
        }

        public Criteria andMontoIn(List<BigDecimal> values) {
            addCriterion("MONTO in", values, "monto");
            return (Criteria) this;
        }

        public Criteria andMontoNotIn(List<BigDecimal> values) {
            addCriterion("MONTO not in", values, "monto");
            return (Criteria) this;
        }

        public Criteria andMontoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MONTO between", value1, value2, "monto");
            return (Criteria) this;
        }

        public Criteria andMontoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MONTO not between", value1, value2, "monto");
            return (Criteria) this;
        }

        public Criteria andModificadoIsNull() {
            addCriterion("MODIFICADO is null");
            return (Criteria) this;
        }

        public Criteria andModificadoIsNotNull() {
            addCriterion("MODIFICADO is not null");
            return (Criteria) this;
        }

        public Criteria andModificadoEqualTo(BigDecimal value) {
            addCriterion("MODIFICADO =", value, "modificado");
            return (Criteria) this;
        }

        public Criteria andModificadoNotEqualTo(BigDecimal value) {
            addCriterion("MODIFICADO <>", value, "modificado");
            return (Criteria) this;
        }

        public Criteria andModificadoGreaterThan(BigDecimal value) {
            addCriterion("MODIFICADO >", value, "modificado");
            return (Criteria) this;
        }

        public Criteria andModificadoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MODIFICADO >=", value, "modificado");
            return (Criteria) this;
        }

        public Criteria andModificadoLessThan(BigDecimal value) {
            addCriterion("MODIFICADO <", value, "modificado");
            return (Criteria) this;
        }

        public Criteria andModificadoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MODIFICADO <=", value, "modificado");
            return (Criteria) this;
        }

        public Criteria andModificadoIn(List<BigDecimal> values) {
            addCriterion("MODIFICADO in", values, "modificado");
            return (Criteria) this;
        }

        public Criteria andModificadoNotIn(List<BigDecimal> values) {
            addCriterion("MODIFICADO not in", values, "modificado");
            return (Criteria) this;
        }

        public Criteria andModificadoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MODIFICADO between", value1, value2, "modificado");
            return (Criteria) this;
        }

        public Criteria andModificadoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MODIFICADO not between", value1, value2, "modificado");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CONTRATO
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}