package mx.gob.shcp.dgtsi.sfu.proyectos.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DetalleCampoProgramaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public DetalleCampoProgramaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdCampoProgramaIsNull() {
            addCriterion("ID_CAMPO_PROGRAMA is null");
            return (Criteria) this;
        }

        public Criteria andIdCampoProgramaIsNotNull() {
            addCriterion("ID_CAMPO_PROGRAMA is not null");
            return (Criteria) this;
        }

        public Criteria andIdCampoProgramaEqualTo(Integer value) {
            addCriterion("ID_CAMPO_PROGRAMA =", value, "idCampoPrograma");
            return (Criteria) this;
        }

        public Criteria andIdCampoProgramaNotEqualTo(Integer value) {
            addCriterion("ID_CAMPO_PROGRAMA <>", value, "idCampoPrograma");
            return (Criteria) this;
        }

        public Criteria andIdCampoProgramaGreaterThan(Integer value) {
            addCriterion("ID_CAMPO_PROGRAMA >", value, "idCampoPrograma");
            return (Criteria) this;
        }

        public Criteria andIdCampoProgramaGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_CAMPO_PROGRAMA >=", value, "idCampoPrograma");
            return (Criteria) this;
        }

        public Criteria andIdCampoProgramaLessThan(Integer value) {
            addCriterion("ID_CAMPO_PROGRAMA <", value, "idCampoPrograma");
            return (Criteria) this;
        }

        public Criteria andIdCampoProgramaLessThanOrEqualTo(Integer value) {
            addCriterion("ID_CAMPO_PROGRAMA <=", value, "idCampoPrograma");
            return (Criteria) this;
        }

        public Criteria andIdCampoProgramaIn(List<Integer> values) {
            addCriterion("ID_CAMPO_PROGRAMA in", values, "idCampoPrograma");
            return (Criteria) this;
        }

        public Criteria andIdCampoProgramaNotIn(List<Integer> values) {
            addCriterion("ID_CAMPO_PROGRAMA not in", values, "idCampoPrograma");
            return (Criteria) this;
        }

        public Criteria andIdCampoProgramaBetween(Integer value1, Integer value2) {
            addCriterion("ID_CAMPO_PROGRAMA between", value1, value2, "idCampoPrograma");
            return (Criteria) this;
        }

        public Criteria andIdCampoProgramaNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_CAMPO_PROGRAMA not between", value1, value2, "idCampoPrograma");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresIsNull() {
            addCriterion("ID_PROGRAMA_PRES is null");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresIsNotNull() {
            addCriterion("ID_PROGRAMA_PRES is not null");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresEqualTo(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES =", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresNotEqualTo(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES <>", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresGreaterThan(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES >", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES >=", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresLessThan(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES <", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES <=", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresIn(List<BigDecimal> values) {
            addCriterion("ID_PROGRAMA_PRES in", values, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresNotIn(List<BigDecimal> values) {
            addCriterion("ID_PROGRAMA_PRES not in", values, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_PROGRAMA_PRES between", value1, value2, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_PROGRAMA_PRES not between", value1, value2, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdCampoIsNull() {
            addCriterion("ID_CAMPO is null");
            return (Criteria) this;
        }

        public Criteria andIdCampoIsNotNull() {
            addCriterion("ID_CAMPO is not null");
            return (Criteria) this;
        }

        public Criteria andIdCampoEqualTo(Integer value) {
            addCriterion("ID_CAMPO =", value, "idCampo");
            return (Criteria) this;
        }

        public Criteria andIdCampoNotEqualTo(Integer value) {
            addCriterion("ID_CAMPO <>", value, "idCampo");
            return (Criteria) this;
        }

        public Criteria andIdCampoGreaterThan(Integer value) {
            addCriterion("ID_CAMPO >", value, "idCampo");
            return (Criteria) this;
        }

        public Criteria andIdCampoGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_CAMPO >=", value, "idCampo");
            return (Criteria) this;
        }

        public Criteria andIdCampoLessThan(Integer value) {
            addCriterion("ID_CAMPO <", value, "idCampo");
            return (Criteria) this;
        }

        public Criteria andIdCampoLessThanOrEqualTo(Integer value) {
            addCriterion("ID_CAMPO <=", value, "idCampo");
            return (Criteria) this;
        }

        public Criteria andIdCampoIn(List<Integer> values) {
            addCriterion("ID_CAMPO in", values, "idCampo");
            return (Criteria) this;
        }

        public Criteria andIdCampoNotIn(List<Integer> values) {
            addCriterion("ID_CAMPO not in", values, "idCampo");
            return (Criteria) this;
        }

        public Criteria andIdCampoBetween(Integer value1, Integer value2) {
            addCriterion("ID_CAMPO between", value1, value2, "idCampo");
            return (Criteria) this;
        }

        public Criteria andIdCampoNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_CAMPO not between", value1, value2, "idCampo");
            return (Criteria) this;
        }

        public Criteria andEstatusIsNull() {
            addCriterion("ESTATUS is null");
            return (Criteria) this;
        }

        public Criteria andEstatusIsNotNull() {
            addCriterion("ESTATUS is not null");
            return (Criteria) this;
        }

        public Criteria andEstatusEqualTo(String value) {
            addCriterion("ESTATUS =", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusNotEqualTo(String value) {
            addCriterion("ESTATUS <>", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusGreaterThan(String value) {
            addCriterion("ESTATUS >", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusGreaterThanOrEqualTo(String value) {
            addCriterion("ESTATUS >=", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusLessThan(String value) {
            addCriterion("ESTATUS <", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusLessThanOrEqualTo(String value) {
            addCriterion("ESTATUS <=", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusLike(String value) {
            addCriterion("ESTATUS like", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusNotLike(String value) {
            addCriterion("ESTATUS not like", value, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusIn(List<String> values) {
            addCriterion("ESTATUS in", values, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusNotIn(List<String> values) {
            addCriterion("ESTATUS not in", values, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusBetween(String value1, String value2) {
            addCriterion("ESTATUS between", value1, value2, "estatus");
            return (Criteria) this;
        }

        public Criteria andEstatusNotBetween(String value1, String value2) {
            addCriterion("ESTATUS not between", value1, value2, "estatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DETALLE_CAMPO_PROGRAMA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}