package mx.gob.shcp.dgtsi.sfu.proyectos.model;

import java.math.BigDecimal;

public class DetalleEjercicioRecurso {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETALLE_EJERCICIO_RECURSO.ID_EJERCICIO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idEjercicioRecurso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETALLE_EJERCICIO_RECURSO.ID_EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idEjercicio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETALLE_EJERCICIO_RECURSO.ID_PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private BigDecimal idProgramaPres;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETALLE_EJERCICIO_RECURSO.ID_EJERCICIO_RECURSO
     *
     * @return the value of DETALLE_EJERCICIO_RECURSO.ID_EJERCICIO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdEjercicioRecurso() {
        return idEjercicioRecurso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETALLE_EJERCICIO_RECURSO.ID_EJERCICIO_RECURSO
     *
     * @param idEjercicioRecurso the value for DETALLE_EJERCICIO_RECURSO.ID_EJERCICIO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdEjercicioRecurso(Integer idEjercicioRecurso) {
        this.idEjercicioRecurso = idEjercicioRecurso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETALLE_EJERCICIO_RECURSO.ID_EJERCICIO
     *
     * @return the value of DETALLE_EJERCICIO_RECURSO.ID_EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdEjercicio() {
        return idEjercicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETALLE_EJERCICIO_RECURSO.ID_EJERCICIO
     *
     * @param idEjercicio the value for DETALLE_EJERCICIO_RECURSO.ID_EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdEjercicio(Integer idEjercicio) {
        this.idEjercicio = idEjercicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETALLE_EJERCICIO_RECURSO.ID_PROGRAMA_PRES
     *
     * @return the value of DETALLE_EJERCICIO_RECURSO.ID_PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public BigDecimal getIdProgramaPres() {
        return idProgramaPres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETALLE_EJERCICIO_RECURSO.ID_PROGRAMA_PRES
     *
     * @param idProgramaPres the value for DETALLE_EJERCICIO_RECURSO.ID_PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdProgramaPres(BigDecimal idProgramaPres) {
        this.idProgramaPres = idProgramaPres;
    }
}