package mx.gob.shcp.dgtsi.sfu.proyectos.model;

public class DetalleAvanceProyecto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETALLE_AVANCE_PROYECTO.ID_DETALLE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idDetalle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETALLE_AVANCE_PROYECTO.ID_PROYECTO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idProyecto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETALLE_AVANCE_PROYECTO.ID_AVANCE_FINANCIERO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idAvanceFinanciero;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETALLE_AVANCE_PROYECTO.ID_AVANCE_FISICO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idAvanceFisico;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETALLE_AVANCE_PROYECTO.STATUS
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETALLE_AVANCE_PROYECTO.ID_DETALLE
     *
     * @return the value of DETALLE_AVANCE_PROYECTO.ID_DETALLE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdDetalle() {
        return idDetalle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETALLE_AVANCE_PROYECTO.ID_DETALLE
     *
     * @param idDetalle the value for DETALLE_AVANCE_PROYECTO.ID_DETALLE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdDetalle(Integer idDetalle) {
        this.idDetalle = idDetalle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETALLE_AVANCE_PROYECTO.ID_PROYECTO
     *
     * @return the value of DETALLE_AVANCE_PROYECTO.ID_PROYECTO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdProyecto() {
        return idProyecto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETALLE_AVANCE_PROYECTO.ID_PROYECTO
     *
     * @param idProyecto the value for DETALLE_AVANCE_PROYECTO.ID_PROYECTO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdProyecto(Integer idProyecto) {
        this.idProyecto = idProyecto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETALLE_AVANCE_PROYECTO.ID_AVANCE_FINANCIERO
     *
     * @return the value of DETALLE_AVANCE_PROYECTO.ID_AVANCE_FINANCIERO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdAvanceFinanciero() {
        return idAvanceFinanciero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETALLE_AVANCE_PROYECTO.ID_AVANCE_FINANCIERO
     *
     * @param idAvanceFinanciero the value for DETALLE_AVANCE_PROYECTO.ID_AVANCE_FINANCIERO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdAvanceFinanciero(Integer idAvanceFinanciero) {
        this.idAvanceFinanciero = idAvanceFinanciero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETALLE_AVANCE_PROYECTO.ID_AVANCE_FISICO
     *
     * @return the value of DETALLE_AVANCE_PROYECTO.ID_AVANCE_FISICO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdAvanceFisico() {
        return idAvanceFisico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETALLE_AVANCE_PROYECTO.ID_AVANCE_FISICO
     *
     * @param idAvanceFisico the value for DETALLE_AVANCE_PROYECTO.ID_AVANCE_FISICO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdAvanceFisico(Integer idAvanceFisico) {
        this.idAvanceFisico = idAvanceFisico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETALLE_AVANCE_PROYECTO.STATUS
     *
     * @return the value of DETALLE_AVANCE_PROYECTO.STATUS
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETALLE_AVANCE_PROYECTO.STATUS
     *
     * @param status the value for DETALLE_AVANCE_PROYECTO.STATUS
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}