package mx.gob.shcp.dgtsi.sfu.proyectos.model;

import java.util.ArrayList;
import java.util.List;

public class DetalleAvanceContratoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public DetalleAvanceContratoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdDetalleAvanceContratoIsNull() {
            addCriterion("ID_DETALLE_AVANCE_CONTRATO is null");
            return (Criteria) this;
        }

        public Criteria andIdDetalleAvanceContratoIsNotNull() {
            addCriterion("ID_DETALLE_AVANCE_CONTRATO is not null");
            return (Criteria) this;
        }

        public Criteria andIdDetalleAvanceContratoEqualTo(Integer value) {
            addCriterion("ID_DETALLE_AVANCE_CONTRATO =", value, "idDetalleAvanceContrato");
            return (Criteria) this;
        }

        public Criteria andIdDetalleAvanceContratoNotEqualTo(Integer value) {
            addCriterion("ID_DETALLE_AVANCE_CONTRATO <>", value, "idDetalleAvanceContrato");
            return (Criteria) this;
        }

        public Criteria andIdDetalleAvanceContratoGreaterThan(Integer value) {
            addCriterion("ID_DETALLE_AVANCE_CONTRATO >", value, "idDetalleAvanceContrato");
            return (Criteria) this;
        }

        public Criteria andIdDetalleAvanceContratoGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_DETALLE_AVANCE_CONTRATO >=", value, "idDetalleAvanceContrato");
            return (Criteria) this;
        }

        public Criteria andIdDetalleAvanceContratoLessThan(Integer value) {
            addCriterion("ID_DETALLE_AVANCE_CONTRATO <", value, "idDetalleAvanceContrato");
            return (Criteria) this;
        }

        public Criteria andIdDetalleAvanceContratoLessThanOrEqualTo(Integer value) {
            addCriterion("ID_DETALLE_AVANCE_CONTRATO <=", value, "idDetalleAvanceContrato");
            return (Criteria) this;
        }

        public Criteria andIdDetalleAvanceContratoIn(List<Integer> values) {
            addCriterion("ID_DETALLE_AVANCE_CONTRATO in", values, "idDetalleAvanceContrato");
            return (Criteria) this;
        }

        public Criteria andIdDetalleAvanceContratoNotIn(List<Integer> values) {
            addCriterion("ID_DETALLE_AVANCE_CONTRATO not in", values, "idDetalleAvanceContrato");
            return (Criteria) this;
        }

        public Criteria andIdDetalleAvanceContratoBetween(Integer value1, Integer value2) {
            addCriterion("ID_DETALLE_AVANCE_CONTRATO between", value1, value2, "idDetalleAvanceContrato");
            return (Criteria) this;
        }

        public Criteria andIdDetalleAvanceContratoNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_DETALLE_AVANCE_CONTRATO not between", value1, value2, "idDetalleAvanceContrato");
            return (Criteria) this;
        }

        public Criteria andIdAvanceProyectoIsNull() {
            addCriterion("ID_AVANCE_PROYECTO is null");
            return (Criteria) this;
        }

        public Criteria andIdAvanceProyectoIsNotNull() {
            addCriterion("ID_AVANCE_PROYECTO is not null");
            return (Criteria) this;
        }

        public Criteria andIdAvanceProyectoEqualTo(Integer value) {
            addCriterion("ID_AVANCE_PROYECTO =", value, "idAvanceProyecto");
            return (Criteria) this;
        }

        public Criteria andIdAvanceProyectoNotEqualTo(Integer value) {
            addCriterion("ID_AVANCE_PROYECTO <>", value, "idAvanceProyecto");
            return (Criteria) this;
        }

        public Criteria andIdAvanceProyectoGreaterThan(Integer value) {
            addCriterion("ID_AVANCE_PROYECTO >", value, "idAvanceProyecto");
            return (Criteria) this;
        }

        public Criteria andIdAvanceProyectoGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_AVANCE_PROYECTO >=", value, "idAvanceProyecto");
            return (Criteria) this;
        }

        public Criteria andIdAvanceProyectoLessThan(Integer value) {
            addCriterion("ID_AVANCE_PROYECTO <", value, "idAvanceProyecto");
            return (Criteria) this;
        }

        public Criteria andIdAvanceProyectoLessThanOrEqualTo(Integer value) {
            addCriterion("ID_AVANCE_PROYECTO <=", value, "idAvanceProyecto");
            return (Criteria) this;
        }

        public Criteria andIdAvanceProyectoIn(List<Integer> values) {
            addCriterion("ID_AVANCE_PROYECTO in", values, "idAvanceProyecto");
            return (Criteria) this;
        }

        public Criteria andIdAvanceProyectoNotIn(List<Integer> values) {
            addCriterion("ID_AVANCE_PROYECTO not in", values, "idAvanceProyecto");
            return (Criteria) this;
        }

        public Criteria andIdAvanceProyectoBetween(Integer value1, Integer value2) {
            addCriterion("ID_AVANCE_PROYECTO between", value1, value2, "idAvanceProyecto");
            return (Criteria) this;
        }

        public Criteria andIdAvanceProyectoNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_AVANCE_PROYECTO not between", value1, value2, "idAvanceProyecto");
            return (Criteria) this;
        }

        public Criteria andIdContratoIsNull() {
            addCriterion("ID_CONTRATO is null");
            return (Criteria) this;
        }

        public Criteria andIdContratoIsNotNull() {
            addCriterion("ID_CONTRATO is not null");
            return (Criteria) this;
        }

        public Criteria andIdContratoEqualTo(Integer value) {
            addCriterion("ID_CONTRATO =", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoNotEqualTo(Integer value) {
            addCriterion("ID_CONTRATO <>", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoGreaterThan(Integer value) {
            addCriterion("ID_CONTRATO >", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_CONTRATO >=", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoLessThan(Integer value) {
            addCriterion("ID_CONTRATO <", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoLessThanOrEqualTo(Integer value) {
            addCriterion("ID_CONTRATO <=", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoIn(List<Integer> values) {
            addCriterion("ID_CONTRATO in", values, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoNotIn(List<Integer> values) {
            addCriterion("ID_CONTRATO not in", values, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoBetween(Integer value1, Integer value2) {
            addCriterion("ID_CONTRATO between", value1, value2, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_CONTRATO not between", value1, value2, "idContrato");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}