package mx.gob.shcp.dgtsi.sfu.proyectos.model;

public class DetalleAvanceContrato {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETALLE_AVANCE_CONTRATO.ID_DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idDetalleAvanceContrato;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETALLE_AVANCE_CONTRATO.ID_AVANCE_PROYECTO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idAvanceProyecto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETALLE_AVANCE_CONTRATO.ID_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idContrato;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETALLE_AVANCE_CONTRATO.ID_DETALLE_AVANCE_CONTRATO
     *
     * @return the value of DETALLE_AVANCE_CONTRATO.ID_DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdDetalleAvanceContrato() {
        return idDetalleAvanceContrato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETALLE_AVANCE_CONTRATO.ID_DETALLE_AVANCE_CONTRATO
     *
     * @param idDetalleAvanceContrato the value for DETALLE_AVANCE_CONTRATO.ID_DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdDetalleAvanceContrato(Integer idDetalleAvanceContrato) {
        this.idDetalleAvanceContrato = idDetalleAvanceContrato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETALLE_AVANCE_CONTRATO.ID_AVANCE_PROYECTO
     *
     * @return the value of DETALLE_AVANCE_CONTRATO.ID_AVANCE_PROYECTO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdAvanceProyecto() {
        return idAvanceProyecto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETALLE_AVANCE_CONTRATO.ID_AVANCE_PROYECTO
     *
     * @param idAvanceProyecto the value for DETALLE_AVANCE_CONTRATO.ID_AVANCE_PROYECTO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdAvanceProyecto(Integer idAvanceProyecto) {
        this.idAvanceProyecto = idAvanceProyecto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETALLE_AVANCE_CONTRATO.ID_CONTRATO
     *
     * @return the value of DETALLE_AVANCE_CONTRATO.ID_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdContrato() {
        return idContrato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETALLE_AVANCE_CONTRATO.ID_CONTRATO
     *
     * @param idContrato the value for DETALLE_AVANCE_CONTRATO.ID_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdContrato(Integer idContrato) {
        this.idContrato = idContrato;
    }
}