package mx.gob.shcp.dgtsi.sfu.proyectos.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DetalleProyectoRecursoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public DetalleProyectoRecursoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdDetalleProyectoRecursoIsNull() {
            addCriterion("ID_DETALLE_PROYECTO_RECURSO is null");
            return (Criteria) this;
        }

        public Criteria andIdDetalleProyectoRecursoIsNotNull() {
            addCriterion("ID_DETALLE_PROYECTO_RECURSO is not null");
            return (Criteria) this;
        }

        public Criteria andIdDetalleProyectoRecursoEqualTo(Integer value) {
            addCriterion("ID_DETALLE_PROYECTO_RECURSO =", value, "idDetalleProyectoRecurso");
            return (Criteria) this;
        }

        public Criteria andIdDetalleProyectoRecursoNotEqualTo(Integer value) {
            addCriterion("ID_DETALLE_PROYECTO_RECURSO <>", value, "idDetalleProyectoRecurso");
            return (Criteria) this;
        }

        public Criteria andIdDetalleProyectoRecursoGreaterThan(Integer value) {
            addCriterion("ID_DETALLE_PROYECTO_RECURSO >", value, "idDetalleProyectoRecurso");
            return (Criteria) this;
        }

        public Criteria andIdDetalleProyectoRecursoGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_DETALLE_PROYECTO_RECURSO >=", value, "idDetalleProyectoRecurso");
            return (Criteria) this;
        }

        public Criteria andIdDetalleProyectoRecursoLessThan(Integer value) {
            addCriterion("ID_DETALLE_PROYECTO_RECURSO <", value, "idDetalleProyectoRecurso");
            return (Criteria) this;
        }

        public Criteria andIdDetalleProyectoRecursoLessThanOrEqualTo(Integer value) {
            addCriterion("ID_DETALLE_PROYECTO_RECURSO <=", value, "idDetalleProyectoRecurso");
            return (Criteria) this;
        }

        public Criteria andIdDetalleProyectoRecursoIn(List<Integer> values) {
            addCriterion("ID_DETALLE_PROYECTO_RECURSO in", values, "idDetalleProyectoRecurso");
            return (Criteria) this;
        }

        public Criteria andIdDetalleProyectoRecursoNotIn(List<Integer> values) {
            addCriterion("ID_DETALLE_PROYECTO_RECURSO not in", values, "idDetalleProyectoRecurso");
            return (Criteria) this;
        }

        public Criteria andIdDetalleProyectoRecursoBetween(Integer value1, Integer value2) {
            addCriterion("ID_DETALLE_PROYECTO_RECURSO between", value1, value2, "idDetalleProyectoRecurso");
            return (Criteria) this;
        }

        public Criteria andIdDetalleProyectoRecursoNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_DETALLE_PROYECTO_RECURSO not between", value1, value2, "idDetalleProyectoRecurso");
            return (Criteria) this;
        }

        public Criteria andIdProyectoIsNull() {
            addCriterion("ID_PROYECTO is null");
            return (Criteria) this;
        }

        public Criteria andIdProyectoIsNotNull() {
            addCriterion("ID_PROYECTO is not null");
            return (Criteria) this;
        }

        public Criteria andIdProyectoEqualTo(Integer value) {
            addCriterion("ID_PROYECTO =", value, "idProyecto");
            return (Criteria) this;
        }

        public Criteria andIdProyectoNotEqualTo(Integer value) {
            addCriterion("ID_PROYECTO <>", value, "idProyecto");
            return (Criteria) this;
        }

        public Criteria andIdProyectoGreaterThan(Integer value) {
            addCriterion("ID_PROYECTO >", value, "idProyecto");
            return (Criteria) this;
        }

        public Criteria andIdProyectoGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_PROYECTO >=", value, "idProyecto");
            return (Criteria) this;
        }

        public Criteria andIdProyectoLessThan(Integer value) {
            addCriterion("ID_PROYECTO <", value, "idProyecto");
            return (Criteria) this;
        }

        public Criteria andIdProyectoLessThanOrEqualTo(Integer value) {
            addCriterion("ID_PROYECTO <=", value, "idProyecto");
            return (Criteria) this;
        }

        public Criteria andIdProyectoIn(List<Integer> values) {
            addCriterion("ID_PROYECTO in", values, "idProyecto");
            return (Criteria) this;
        }

        public Criteria andIdProyectoNotIn(List<Integer> values) {
            addCriterion("ID_PROYECTO not in", values, "idProyecto");
            return (Criteria) this;
        }

        public Criteria andIdProyectoBetween(Integer value1, Integer value2) {
            addCriterion("ID_PROYECTO between", value1, value2, "idProyecto");
            return (Criteria) this;
        }

        public Criteria andIdProyectoNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_PROYECTO not between", value1, value2, "idProyecto");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresIsNull() {
            addCriterion("ID_PROGRAMA_PRES is null");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresIsNotNull() {
            addCriterion("ID_PROGRAMA_PRES is not null");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresEqualTo(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES =", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresNotEqualTo(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES <>", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresGreaterThan(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES >", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES >=", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresLessThan(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES <", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES <=", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresIn(List<BigDecimal> values) {
            addCriterion("ID_PROGRAMA_PRES in", values, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresNotIn(List<BigDecimal> values) {
            addCriterion("ID_PROGRAMA_PRES not in", values, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_PROGRAMA_PRES between", value1, value2, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_PROGRAMA_PRES not between", value1, value2, "idProgramaPres");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}