package mx.gob.shcp.dgtsi.sfu.proyectos.model;

public class Ejercicio {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EJERCICIO.ID_EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idEjercicio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EJERCICIO.CICLO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Short ciclo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EJERCICIO.ID_MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idMunicipio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EJERCICIO.ID_EJERCICIO
     *
     * @return the value of EJERCICIO.ID_EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdEjercicio() {
        return idEjercicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EJERCICIO.ID_EJERCICIO
     *
     * @param idEjercicio the value for EJERCICIO.ID_EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdEjercicio(Integer idEjercicio) {
        this.idEjercicio = idEjercicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EJERCICIO.CICLO
     *
     * @return the value of EJERCICIO.CICLO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Short getCiclo() {
        return ciclo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EJERCICIO.CICLO
     *
     * @param ciclo the value for EJERCICIO.CICLO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setCiclo(Short ciclo) {
        this.ciclo = ciclo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EJERCICIO.ID_MUNICIPIO
     *
     * @return the value of EJERCICIO.ID_MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdMunicipio() {
        return idMunicipio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EJERCICIO.ID_MUNICIPIO
     *
     * @param idMunicipio the value for EJERCICIO.ID_MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
}