package mx.gob.shcp.dgtsi.sfu.proyectos.model;

import java.math.BigDecimal;

public class Institucion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUCION.ID_INSTITUCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private BigDecimal idInstitucion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUCION.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private String descripcion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUCION.ID_MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idMunicipio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUCION.ID_USUARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idUsuario;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUCION.ID_INSTITUCION
     *
     * @return the value of INSTITUCION.ID_INSTITUCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public BigDecimal getIdInstitucion() {
        return idInstitucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUCION.ID_INSTITUCION
     *
     * @param idInstitucion the value for INSTITUCION.ID_INSTITUCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdInstitucion(BigDecimal idInstitucion) {
        this.idInstitucion = idInstitucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUCION.DESCRIPCION
     *
     * @return the value of INSTITUCION.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUCION.DESCRIPCION
     *
     * @param descripcion the value for INSTITUCION.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUCION.ID_MUNICIPIO
     *
     * @return the value of INSTITUCION.ID_MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdMunicipio() {
        return idMunicipio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUCION.ID_MUNICIPIO
     *
     * @param idMunicipio the value for INSTITUCION.ID_MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUCION.ID_USUARIO
     *
     * @return the value of INSTITUCION.ID_USUARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUCION.ID_USUARIO
     *
     * @param idUsuario the value for INSTITUCION.ID_USUARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
}