package mx.gob.shcp.dgtsi.sfu.proyectos.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class MapaAvanceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public MapaAvanceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdMapaAvanceIsNull() {
            addCriterion("ID_MAPA_AVANCE is null");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceIsNotNull() {
            addCriterion("ID_MAPA_AVANCE is not null");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceEqualTo(Integer value) {
            addCriterion("ID_MAPA_AVANCE =", value, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceNotEqualTo(Integer value) {
            addCriterion("ID_MAPA_AVANCE <>", value, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceGreaterThan(Integer value) {
            addCriterion("ID_MAPA_AVANCE >", value, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_MAPA_AVANCE >=", value, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceLessThan(Integer value) {
            addCriterion("ID_MAPA_AVANCE <", value, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceLessThanOrEqualTo(Integer value) {
            addCriterion("ID_MAPA_AVANCE <=", value, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceIn(List<Integer> values) {
            addCriterion("ID_MAPA_AVANCE in", values, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceNotIn(List<Integer> values) {
            addCriterion("ID_MAPA_AVANCE not in", values, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceBetween(Integer value1, Integer value2) {
            addCriterion("ID_MAPA_AVANCE between", value1, value2, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andIdMapaAvanceNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_MAPA_AVANCE not between", value1, value2, "idMapaAvance");
            return (Criteria) this;
        }

        public Criteria andLongitudIsNull() {
            addCriterion("LONGITUD is null");
            return (Criteria) this;
        }

        public Criteria andLongitudIsNotNull() {
            addCriterion("LONGITUD is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudEqualTo(BigDecimal value) {
            addCriterion("LONGITUD =", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudNotEqualTo(BigDecimal value) {
            addCriterion("LONGITUD <>", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudGreaterThan(BigDecimal value) {
            addCriterion("LONGITUD >", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LONGITUD >=", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudLessThan(BigDecimal value) {
            addCriterion("LONGITUD <", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LONGITUD <=", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudIn(List<BigDecimal> values) {
            addCriterion("LONGITUD in", values, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudNotIn(List<BigDecimal> values) {
            addCriterion("LONGITUD not in", values, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LONGITUD between", value1, value2, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LONGITUD not between", value1, value2, "longitud");
            return (Criteria) this;
        }

        public Criteria andLatitudIsNull() {
            addCriterion("LATITUD is null");
            return (Criteria) this;
        }

        public Criteria andLatitudIsNotNull() {
            addCriterion("LATITUD is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudEqualTo(BigDecimal value) {
            addCriterion("LATITUD =", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudNotEqualTo(BigDecimal value) {
            addCriterion("LATITUD <>", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudGreaterThan(BigDecimal value) {
            addCriterion("LATITUD >", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LATITUD >=", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudLessThan(BigDecimal value) {
            addCriterion("LATITUD <", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LATITUD <=", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudIn(List<BigDecimal> values) {
            addCriterion("LATITUD in", values, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudNotIn(List<BigDecimal> values) {
            addCriterion("LATITUD not in", values, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LATITUD between", value1, value2, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LATITUD not between", value1, value2, "latitud");
            return (Criteria) this;
        }

        public Criteria andDireccionIsNull() {
            addCriterion("DIRECCION is null");
            return (Criteria) this;
        }

        public Criteria andDireccionIsNotNull() {
            addCriterion("DIRECCION is not null");
            return (Criteria) this;
        }

        public Criteria andDireccionEqualTo(String value) {
            addCriterion("DIRECCION =", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionNotEqualTo(String value) {
            addCriterion("DIRECCION <>", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionGreaterThan(String value) {
            addCriterion("DIRECCION >", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionGreaterThanOrEqualTo(String value) {
            addCriterion("DIRECCION >=", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionLessThan(String value) {
            addCriterion("DIRECCION <", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionLessThanOrEqualTo(String value) {
            addCriterion("DIRECCION <=", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionLike(String value) {
            addCriterion("DIRECCION like", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionNotLike(String value) {
            addCriterion("DIRECCION not like", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionIn(List<String> values) {
            addCriterion("DIRECCION in", values, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionNotIn(List<String> values) {
            addCriterion("DIRECCION not in", values, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionBetween(String value1, String value2) {
            addCriterion("DIRECCION between", value1, value2, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionNotBetween(String value1, String value2) {
            addCriterion("DIRECCION not between", value1, value2, "direccion");
            return (Criteria) this;
        }

        public Criteria andOrdenIsNull() {
            addCriterion("ORDEN is null");
            return (Criteria) this;
        }

        public Criteria andOrdenIsNotNull() {
            addCriterion("ORDEN is not null");
            return (Criteria) this;
        }

        public Criteria andOrdenEqualTo(Integer value) {
            addCriterion("ORDEN =", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenNotEqualTo(Integer value) {
            addCriterion("ORDEN <>", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenGreaterThan(Integer value) {
            addCriterion("ORDEN >", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDEN >=", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenLessThan(Integer value) {
            addCriterion("ORDEN <", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenLessThanOrEqualTo(Integer value) {
            addCriterion("ORDEN <=", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenIn(List<Integer> values) {
            addCriterion("ORDEN in", values, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenNotIn(List<Integer> values) {
            addCriterion("ORDEN not in", values, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenBetween(Integer value1, Integer value2) {
            addCriterion("ORDEN between", value1, value2, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDEN not between", value1, value2, "orden");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}