package mx.gob.shcp.dgtsi.sfu.proyectos.model;

import java.math.BigDecimal;

public class MapaAvance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAPA_AVANCE.ID_MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idMapaAvance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAPA_AVANCE.LONGITUD
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private BigDecimal longitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAPA_AVANCE.LATITUD
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private BigDecimal latitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAPA_AVANCE.DIRECCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private String direccion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAPA_AVANCE.ORDEN
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer orden;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAPA_AVANCE.ID_MAPA_AVANCE
     *
     * @return the value of MAPA_AVANCE.ID_MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdMapaAvance() {
        return idMapaAvance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAPA_AVANCE.ID_MAPA_AVANCE
     *
     * @param idMapaAvance the value for MAPA_AVANCE.ID_MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdMapaAvance(Integer idMapaAvance) {
        this.idMapaAvance = idMapaAvance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAPA_AVANCE.LONGITUD
     *
     * @return the value of MAPA_AVANCE.LONGITUD
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public BigDecimal getLongitud() {
        return longitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAPA_AVANCE.LONGITUD
     *
     * @param longitud the value for MAPA_AVANCE.LONGITUD
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setLongitud(BigDecimal longitud) {
        this.longitud = longitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAPA_AVANCE.LATITUD
     *
     * @return the value of MAPA_AVANCE.LATITUD
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public BigDecimal getLatitud() {
        return latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAPA_AVANCE.LATITUD
     *
     * @param latitud the value for MAPA_AVANCE.LATITUD
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setLatitud(BigDecimal latitud) {
        this.latitud = latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAPA_AVANCE.DIRECCION
     *
     * @return the value of MAPA_AVANCE.DIRECCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAPA_AVANCE.DIRECCION
     *
     * @param direccion the value for MAPA_AVANCE.DIRECCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion == null ? null : direccion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAPA_AVANCE.ORDEN
     *
     * @return the value of MAPA_AVANCE.ORDEN
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getOrden() {
        return orden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAPA_AVANCE.ORDEN
     *
     * @param orden the value for MAPA_AVANCE.ORDEN
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setOrden(Integer orden) {
        this.orden = orden;
    }
}