package mx.gob.shcp.dgtsi.sfu.proyectos.model;

import java.util.ArrayList;
import java.util.List;

public class PartidaGenericaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public PartidaGenericaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdPartidaIsNull() {
            addCriterion("ID_PARTIDA is null");
            return (Criteria) this;
        }

        public Criteria andIdPartidaIsNotNull() {
            addCriterion("ID_PARTIDA is not null");
            return (Criteria) this;
        }

        public Criteria andIdPartidaEqualTo(Integer value) {
            addCriterion("ID_PARTIDA =", value, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaNotEqualTo(Integer value) {
            addCriterion("ID_PARTIDA <>", value, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaGreaterThan(Integer value) {
            addCriterion("ID_PARTIDA >", value, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_PARTIDA >=", value, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaLessThan(Integer value) {
            addCriterion("ID_PARTIDA <", value, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaLessThanOrEqualTo(Integer value) {
            addCriterion("ID_PARTIDA <=", value, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaIn(List<Integer> values) {
            addCriterion("ID_PARTIDA in", values, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaNotIn(List<Integer> values) {
            addCriterion("ID_PARTIDA not in", values, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaBetween(Integer value1, Integer value2) {
            addCriterion("ID_PARTIDA between", value1, value2, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_PARTIDA not between", value1, value2, "idPartida");
            return (Criteria) this;
        }

        public Criteria andPartidaIsNull() {
            addCriterion("PARTIDA is null");
            return (Criteria) this;
        }

        public Criteria andPartidaIsNotNull() {
            addCriterion("PARTIDA is not null");
            return (Criteria) this;
        }

        public Criteria andPartidaEqualTo(String value) {
            addCriterion("PARTIDA =", value, "partida");
            return (Criteria) this;
        }

        public Criteria andPartidaNotEqualTo(String value) {
            addCriterion("PARTIDA <>", value, "partida");
            return (Criteria) this;
        }

        public Criteria andPartidaGreaterThan(String value) {
            addCriterion("PARTIDA >", value, "partida");
            return (Criteria) this;
        }

        public Criteria andPartidaGreaterThanOrEqualTo(String value) {
            addCriterion("PARTIDA >=", value, "partida");
            return (Criteria) this;
        }

        public Criteria andPartidaLessThan(String value) {
            addCriterion("PARTIDA <", value, "partida");
            return (Criteria) this;
        }

        public Criteria andPartidaLessThanOrEqualTo(String value) {
            addCriterion("PARTIDA <=", value, "partida");
            return (Criteria) this;
        }

        public Criteria andPartidaLike(String value) {
            addCriterion("PARTIDA like", value, "partida");
            return (Criteria) this;
        }

        public Criteria andPartidaNotLike(String value) {
            addCriterion("PARTIDA not like", value, "partida");
            return (Criteria) this;
        }

        public Criteria andPartidaIn(List<String> values) {
            addCriterion("PARTIDA in", values, "partida");
            return (Criteria) this;
        }

        public Criteria andPartidaNotIn(List<String> values) {
            addCriterion("PARTIDA not in", values, "partida");
            return (Criteria) this;
        }

        public Criteria andPartidaBetween(String value1, String value2) {
            addCriterion("PARTIDA between", value1, value2, "partida");
            return (Criteria) this;
        }

        public Criteria andPartidaNotBetween(String value1, String value2) {
            addCriterion("PARTIDA not between", value1, value2, "partida");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("DESCRIPCION is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("DESCRIPCION is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("DESCRIPCION =", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("DESCRIPCION <>", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("DESCRIPCION >", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION >=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("DESCRIPCION <", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION <=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("DESCRIPCION like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("DESCRIPCION not like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("DESCRIPCION in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("DESCRIPCION not in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("DESCRIPCION between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPCION not between", value1, value2, "descripcion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}