package mx.gob.shcp.dgtsi.sfu.proyectos.model;

public class PartidaGenerica {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTIDA_GENERICA.ID_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idPartida;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTIDA_GENERICA.PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private String partida;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PARTIDA_GENERICA.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private String descripcion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTIDA_GENERICA.ID_PARTIDA
     *
     * @return the value of PARTIDA_GENERICA.ID_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdPartida() {
        return idPartida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTIDA_GENERICA.ID_PARTIDA
     *
     * @param idPartida the value for PARTIDA_GENERICA.ID_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdPartida(Integer idPartida) {
        this.idPartida = idPartida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTIDA_GENERICA.PARTIDA
     *
     * @return the value of PARTIDA_GENERICA.PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getPartida() {
        return partida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTIDA_GENERICA.PARTIDA
     *
     * @param partida the value for PARTIDA_GENERICA.PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setPartida(String partida) {
        this.partida = partida == null ? null : partida.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTIDA_GENERICA.DESCRIPCION
     *
     * @return the value of PARTIDA_GENERICA.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTIDA_GENERICA.DESCRIPCION
     *
     * @param descripcion the value for PARTIDA_GENERICA.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }
}