package mx.gob.shcp.dgtsi.sfu.proyectos.model;

import java.math.BigDecimal;

public class ProgramaPartida {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROGRAMA_PARTIDA.ID_PROG_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private String idProgPartida;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROGRAMA_PARTIDA.ID_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idPartida;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROGRAMA_PARTIDA.ID_PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private BigDecimal idProgramaPres;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROGRAMA_PARTIDA.ID_PROG_PARTIDA
     *
     * @return the value of PROGRAMA_PARTIDA.ID_PROG_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getIdProgPartida() {
        return idProgPartida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROGRAMA_PARTIDA.ID_PROG_PARTIDA
     *
     * @param idProgPartida the value for PROGRAMA_PARTIDA.ID_PROG_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdProgPartida(String idProgPartida) {
        this.idProgPartida = idProgPartida == null ? null : idProgPartida.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROGRAMA_PARTIDA.ID_PARTIDA
     *
     * @return the value of PROGRAMA_PARTIDA.ID_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdPartida() {
        return idPartida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROGRAMA_PARTIDA.ID_PARTIDA
     *
     * @param idPartida the value for PROGRAMA_PARTIDA.ID_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdPartida(Integer idPartida) {
        this.idPartida = idPartida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROGRAMA_PARTIDA.ID_PROGRAMA_PRES
     *
     * @return the value of PROGRAMA_PARTIDA.ID_PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public BigDecimal getIdProgramaPres() {
        return idProgramaPres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROGRAMA_PARTIDA.ID_PROGRAMA_PRES
     *
     * @param idProgramaPres the value for PROGRAMA_PARTIDA.ID_PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdProgramaPres(BigDecimal idProgramaPres) {
        this.idProgramaPres = idProgramaPres;
    }
}