package mx.gob.shcp.dgtsi.sfu.proyectos.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ProgramaPartidaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public ProgramaPartidaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdProgPartidaIsNull() {
            addCriterion("ID_PROG_PARTIDA is null");
            return (Criteria) this;
        }

        public Criteria andIdProgPartidaIsNotNull() {
            addCriterion("ID_PROG_PARTIDA is not null");
            return (Criteria) this;
        }

        public Criteria andIdProgPartidaEqualTo(String value) {
            addCriterion("ID_PROG_PARTIDA =", value, "idProgPartida");
            return (Criteria) this;
        }

        public Criteria andIdProgPartidaNotEqualTo(String value) {
            addCriterion("ID_PROG_PARTIDA <>", value, "idProgPartida");
            return (Criteria) this;
        }

        public Criteria andIdProgPartidaGreaterThan(String value) {
            addCriterion("ID_PROG_PARTIDA >", value, "idProgPartida");
            return (Criteria) this;
        }

        public Criteria andIdProgPartidaGreaterThanOrEqualTo(String value) {
            addCriterion("ID_PROG_PARTIDA >=", value, "idProgPartida");
            return (Criteria) this;
        }

        public Criteria andIdProgPartidaLessThan(String value) {
            addCriterion("ID_PROG_PARTIDA <", value, "idProgPartida");
            return (Criteria) this;
        }

        public Criteria andIdProgPartidaLessThanOrEqualTo(String value) {
            addCriterion("ID_PROG_PARTIDA <=", value, "idProgPartida");
            return (Criteria) this;
        }

        public Criteria andIdProgPartidaLike(String value) {
            addCriterion("ID_PROG_PARTIDA like", value, "idProgPartida");
            return (Criteria) this;
        }

        public Criteria andIdProgPartidaNotLike(String value) {
            addCriterion("ID_PROG_PARTIDA not like", value, "idProgPartida");
            return (Criteria) this;
        }

        public Criteria andIdProgPartidaIn(List<String> values) {
            addCriterion("ID_PROG_PARTIDA in", values, "idProgPartida");
            return (Criteria) this;
        }

        public Criteria andIdProgPartidaNotIn(List<String> values) {
            addCriterion("ID_PROG_PARTIDA not in", values, "idProgPartida");
            return (Criteria) this;
        }

        public Criteria andIdProgPartidaBetween(String value1, String value2) {
            addCriterion("ID_PROG_PARTIDA between", value1, value2, "idProgPartida");
            return (Criteria) this;
        }

        public Criteria andIdProgPartidaNotBetween(String value1, String value2) {
            addCriterion("ID_PROG_PARTIDA not between", value1, value2, "idProgPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaIsNull() {
            addCriterion("ID_PARTIDA is null");
            return (Criteria) this;
        }

        public Criteria andIdPartidaIsNotNull() {
            addCriterion("ID_PARTIDA is not null");
            return (Criteria) this;
        }

        public Criteria andIdPartidaEqualTo(Integer value) {
            addCriterion("ID_PARTIDA =", value, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaNotEqualTo(Integer value) {
            addCriterion("ID_PARTIDA <>", value, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaGreaterThan(Integer value) {
            addCriterion("ID_PARTIDA >", value, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_PARTIDA >=", value, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaLessThan(Integer value) {
            addCriterion("ID_PARTIDA <", value, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaLessThanOrEqualTo(Integer value) {
            addCriterion("ID_PARTIDA <=", value, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaIn(List<Integer> values) {
            addCriterion("ID_PARTIDA in", values, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaNotIn(List<Integer> values) {
            addCriterion("ID_PARTIDA not in", values, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaBetween(Integer value1, Integer value2) {
            addCriterion("ID_PARTIDA between", value1, value2, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdPartidaNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_PARTIDA not between", value1, value2, "idPartida");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresIsNull() {
            addCriterion("ID_PROGRAMA_PRES is null");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresIsNotNull() {
            addCriterion("ID_PROGRAMA_PRES is not null");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresEqualTo(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES =", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresNotEqualTo(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES <>", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresGreaterThan(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES >", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES >=", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresLessThan(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES <", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_PROGRAMA_PRES <=", value, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresIn(List<BigDecimal> values) {
            addCriterion("ID_PROGRAMA_PRES in", values, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresNotIn(List<BigDecimal> values) {
            addCriterion("ID_PROGRAMA_PRES not in", values, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_PROGRAMA_PRES between", value1, value2, "idProgramaPres");
            return (Criteria) this;
        }

        public Criteria andIdProgramaPresNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_PROGRAMA_PRES not between", value1, value2, "idProgramaPres");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}