package mx.gob.shcp.dgtsi.sfu.proyectos.model;

import java.math.BigDecimal;

public class ProgramaPres {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROGRAMA_PRES.ID_PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private BigDecimal idProgramaPres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROGRAMA_PRES.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private String descripcion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROGRAMA_PRES.PP
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private String pp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROGRAMA_PRES.MONTO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private BigDecimal monto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROGRAMA_PRES.ID_RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idRamo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROGRAMA_PRES.ID_PROGRAMA_PRES
     *
     * @return the value of PROGRAMA_PRES.ID_PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public BigDecimal getIdProgramaPres() {
        return idProgramaPres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROGRAMA_PRES.ID_PROGRAMA_PRES
     *
     * @param idProgramaPres the value for PROGRAMA_PRES.ID_PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdProgramaPres(BigDecimal idProgramaPres) {
        this.idProgramaPres = idProgramaPres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROGRAMA_PRES.DESCRIPCION
     *
     * @return the value of PROGRAMA_PRES.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROGRAMA_PRES.DESCRIPCION
     *
     * @param descripcion the value for PROGRAMA_PRES.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROGRAMA_PRES.PP
     *
     * @return the value of PROGRAMA_PRES.PP
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getPp() {
        return pp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROGRAMA_PRES.PP
     *
     * @param pp the value for PROGRAMA_PRES.PP
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setPp(String pp) {
        this.pp = pp == null ? null : pp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROGRAMA_PRES.MONTO
     *
     * @return the value of PROGRAMA_PRES.MONTO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public BigDecimal getMonto() {
        return monto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROGRAMA_PRES.MONTO
     *
     * @param monto the value for PROGRAMA_PRES.MONTO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROGRAMA_PRES.ID_RAMO
     *
     * @return the value of PROGRAMA_PRES.ID_RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdRamo() {
        return idRamo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROGRAMA_PRES.ID_RAMO
     *
     * @param idRamo the value for PROGRAMA_PRES.ID_RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdRamo(Integer idRamo) {
        this.idRamo = idRamo;
    }
}