package mx.gob.shcp.dgtsi.sfu.proyectos.model;

public class Ramo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAMO.ID_RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idRamo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAMO.RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private String ramo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAMO.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private String descripcion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RAMO.ID_TIPO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idTipoRecurso;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAMO.ID_RAMO
     *
     * @return the value of RAMO.ID_RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdRamo() {
        return idRamo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAMO.ID_RAMO
     *
     * @param idRamo the value for RAMO.ID_RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdRamo(Integer idRamo) {
        this.idRamo = idRamo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAMO.RAMO
     *
     * @return the value of RAMO.RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getRamo() {
        return ramo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAMO.RAMO
     *
     * @param ramo the value for RAMO.RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setRamo(String ramo) {
        this.ramo = ramo == null ? null : ramo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAMO.DESCRIPCION
     *
     * @return the value of RAMO.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAMO.DESCRIPCION
     *
     * @param descripcion the value for RAMO.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RAMO.ID_TIPO_RECURSO
     *
     * @return the value of RAMO.ID_TIPO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdTipoRecurso() {
        return idTipoRecurso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RAMO.ID_TIPO_RECURSO
     *
     * @param idTipoRecurso the value for RAMO.ID_TIPO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdTipoRecurso(Integer idTipoRecurso) {
        this.idTipoRecurso = idTipoRecurso;
    }
}