package mx.gob.shcp.dgtsi.sfu.proyectos.model;

public class TipoProyectoCat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIPO_PROYECTO_CAT.ID_TIPO_PROYECTO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idTipoProyecto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIPO_PROYECTO_CAT.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private String descripcion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIPO_PROYECTO_CAT.ID_TIPO_PROYECTO
     *
     * @return the value of TIPO_PROYECTO_CAT.ID_TIPO_PROYECTO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdTipoProyecto() {
        return idTipoProyecto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIPO_PROYECTO_CAT.ID_TIPO_PROYECTO
     *
     * @param idTipoProyecto the value for TIPO_PROYECTO_CAT.ID_TIPO_PROYECTO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdTipoProyecto(Integer idTipoProyecto) {
        this.idTipoProyecto = idTipoProyecto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIPO_PROYECTO_CAT.DESCRIPCION
     *
     * @return the value of TIPO_PROYECTO_CAT.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIPO_PROYECTO_CAT.DESCRIPCION
     *
     * @param descripcion the value for TIPO_PROYECTO_CAT.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }
}