package mx.gob.shcp.dgtsi.sfu.administracion.model;

import java.math.BigDecimal;

public class DetalleUsuarioRol {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETALLE_USUARIO_ROL.ID_USUARIO_ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private BigDecimal idUsuarioRol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETALLE_USUARIO_ROL.ID_USUARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private Integer idUsuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETALLE_USUARIO_ROL.ID_ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private BigDecimal idRol;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETALLE_USUARIO_ROL.ID_USUARIO_ROL
     *
     * @return the value of DETALLE_USUARIO_ROL.ID_USUARIO_ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public BigDecimal getIdUsuarioRol() {
        return idUsuarioRol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETALLE_USUARIO_ROL.ID_USUARIO_ROL
     *
     * @param idUsuarioRol the value for DETALLE_USUARIO_ROL.ID_USUARIO_ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdUsuarioRol(BigDecimal idUsuarioRol) {
        this.idUsuarioRol = idUsuarioRol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETALLE_USUARIO_ROL.ID_USUARIO
     *
     * @return the value of DETALLE_USUARIO_ROL.ID_USUARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETALLE_USUARIO_ROL.ID_USUARIO
     *
     * @param idUsuario the value for DETALLE_USUARIO_ROL.ID_USUARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETALLE_USUARIO_ROL.ID_ROL
     *
     * @return the value of DETALLE_USUARIO_ROL.ID_ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public BigDecimal getIdRol() {
        return idRol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETALLE_USUARIO_ROL.ID_ROL
     *
     * @param idRol the value for DETALLE_USUARIO_ROL.ID_ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdRol(BigDecimal idRol) {
        this.idRol = idRol;
    }
}