package mx.gob.shcp.dgtsi.sfu.administracion.model;

import java.math.BigDecimal;

public class Rol {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROL.ID_ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private BigDecimal idRol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROL.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    private String descripcion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROL.ID_ROL
     *
     * @return the value of ROL.ID_ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public BigDecimal getIdRol() {
        return idRol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROL.ID_ROL
     *
     * @param idRol the value for ROL.ID_ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setIdRol(BigDecimal idRol) {
        this.idRol = idRol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROL.DESCRIPCION
     *
     * @return the value of ROL.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROL.DESCRIPCION
     *
     * @param descripcion the value for ROL.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }
}