package mx.gob.shcp.dgtsi.sfu.administracion.repository;

import java.math.BigDecimal;
import java.util.List;
import mx.gob.shcp.dgtsi.sfu.administracion.model.Rol;
import mx.gob.shcp.dgtsi.sfu.administracion.model.RolExample;
import org.apache.ibatis.annotations.Param;

public interface RolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(RolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(RolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(BigDecimal idRol);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(Rol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(Rol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<Rol> selectByExample(RolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    Rol selectByPrimaryKey(BigDecimal idRol);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Rol record, @Param("example") RolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") Rol record, @Param("example") RolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(Rol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(Rol record);
}