package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.AvanceFisicoMapa;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.AvanceFisicoMapaExample;
import org.apache.ibatis.annotations.Param;

public interface AvanceFisicoMapaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(AvanceFisicoMapaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(AvanceFisicoMapaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(Integer idAvanceFisicoMapa);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(AvanceFisicoMapa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(AvanceFisicoMapa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<AvanceFisicoMapa> selectByExample(AvanceFisicoMapaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    AvanceFisicoMapa selectByPrimaryKey(Integer idAvanceFisicoMapa);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") AvanceFisicoMapa record, @Param("example") AvanceFisicoMapaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") AvanceFisicoMapa record, @Param("example") AvanceFisicoMapaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(AvanceFisicoMapa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FISICO_MAPA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(AvanceFisicoMapa record);
}