package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.AvanceFinanciero;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.AvanceFinancieroExample;
import org.apache.ibatis.annotations.Param;

public interface AvanceFinancieroMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FINANCIERO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(AvanceFinancieroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FINANCIERO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(AvanceFinancieroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FINANCIERO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(Integer idAvanceFinanciero);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FINANCIERO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(AvanceFinanciero record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FINANCIERO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(AvanceFinanciero record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FINANCIERO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<AvanceFinanciero> selectByExample(AvanceFinancieroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FINANCIERO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    AvanceFinanciero selectByPrimaryKey(Integer idAvanceFinanciero);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FINANCIERO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") AvanceFinanciero record, @Param("example") AvanceFinancieroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FINANCIERO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") AvanceFinanciero record, @Param("example") AvanceFinancieroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FINANCIERO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(AvanceFinanciero record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AVANCE_FINANCIERO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(AvanceFinanciero record);
}