package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.Beneficiario;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.BeneficiarioExample;
import org.apache.ibatis.annotations.Param;

public interface BeneficiarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BENEFICIARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(BeneficiarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BENEFICIARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(BeneficiarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BENEFICIARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(Integer idBeneficiario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BENEFICIARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(Beneficiario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BENEFICIARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(Beneficiario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BENEFICIARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<Beneficiario> selectByExample(BeneficiarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BENEFICIARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    Beneficiario selectByPrimaryKey(Integer idBeneficiario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BENEFICIARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Beneficiario record, @Param("example") BeneficiarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BENEFICIARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") Beneficiario record, @Param("example") BeneficiarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BENEFICIARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(Beneficiario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BENEFICIARIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(Beneficiario record);
}