package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.ClasifProyectoCat;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.ClasifProyectoCatExample;
import org.apache.ibatis.annotations.Param;

public interface ClasifProyectoCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASIF_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(ClasifProyectoCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASIF_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(ClasifProyectoCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASIF_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(Integer idClasifProyecto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASIF_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(ClasifProyectoCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASIF_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(ClasifProyectoCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASIF_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<ClasifProyectoCat> selectByExample(ClasifProyectoCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASIF_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    ClasifProyectoCat selectByPrimaryKey(Integer idClasifProyecto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASIF_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") ClasifProyectoCat record, @Param("example") ClasifProyectoCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASIF_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") ClasifProyectoCat record, @Param("example") ClasifProyectoCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASIF_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(ClasifProyectoCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLASIF_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(ClasifProyectoCat record);
}