package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.DetalleAvanceContrato;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.DetalleAvanceContratoExample;
import org.apache.ibatis.annotations.Param;

public interface DetalleAvanceContratoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(DetalleAvanceContratoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(DetalleAvanceContratoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(Integer idDetalleAvanceContrato);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(DetalleAvanceContrato record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(DetalleAvanceContrato record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<DetalleAvanceContrato> selectByExample(DetalleAvanceContratoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    DetalleAvanceContrato selectByPrimaryKey(Integer idDetalleAvanceContrato);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") DetalleAvanceContrato record, @Param("example") DetalleAvanceContratoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") DetalleAvanceContrato record, @Param("example") DetalleAvanceContratoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(DetalleAvanceContrato record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_AVANCE_CONTRATO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(DetalleAvanceContrato record);
}