package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.DetalleProyectoRecurso;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.DetalleProyectoRecursoExample;
import org.apache.ibatis.annotations.Param;

public interface DetalleProyectoRecursoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(DetalleProyectoRecursoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(DetalleProyectoRecursoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(Integer idDetalleProyectoRecurso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(DetalleProyectoRecurso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(DetalleProyectoRecurso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<DetalleProyectoRecurso> selectByExample(DetalleProyectoRecursoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    DetalleProyectoRecurso selectByPrimaryKey(Integer idDetalleProyectoRecurso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") DetalleProyectoRecurso record, @Param("example") DetalleProyectoRecursoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") DetalleProyectoRecurso record, @Param("example") DetalleProyectoRecursoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(DetalleProyectoRecurso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_PROYECTO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(DetalleProyectoRecurso record);
}