package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.DetalleEjercicioRecurso;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.DetalleEjercicioRecursoExample;
import org.apache.ibatis.annotations.Param;

public interface DetalleEjercicioRecursoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_EJERCICIO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(DetalleEjercicioRecursoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_EJERCICIO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(DetalleEjercicioRecursoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_EJERCICIO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(Integer idEjercicioRecurso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_EJERCICIO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(DetalleEjercicioRecurso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_EJERCICIO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(DetalleEjercicioRecurso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_EJERCICIO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<DetalleEjercicioRecurso> selectByExample(DetalleEjercicioRecursoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_EJERCICIO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    DetalleEjercicioRecurso selectByPrimaryKey(Integer idEjercicioRecurso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_EJERCICIO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") DetalleEjercicioRecurso record, @Param("example") DetalleEjercicioRecursoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_EJERCICIO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") DetalleEjercicioRecurso record, @Param("example") DetalleEjercicioRecursoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_EJERCICIO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(DetalleEjercicioRecurso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DETALLE_EJERCICIO_RECURSO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(DetalleEjercicioRecurso record);
}