package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.Ejercicio;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.EjercicioExample;
import org.apache.ibatis.annotations.Param;

public interface EjercicioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(EjercicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(EjercicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(Integer idEjercicio);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(Ejercicio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(Ejercicio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<Ejercicio> selectByExample(EjercicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    Ejercicio selectByPrimaryKey(Integer idEjercicio);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Ejercicio record, @Param("example") EjercicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") Ejercicio record, @Param("example") EjercicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(Ejercicio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EJERCICIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(Ejercicio record);
}