package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.ImagenesAvance;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.ImagenesAvanceExample;
import org.apache.ibatis.annotations.Param;

public interface ImagenesAvanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGENES_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(ImagenesAvanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGENES_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(ImagenesAvanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGENES_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(Integer idImagenesAvance);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGENES_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(ImagenesAvance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGENES_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(ImagenesAvance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGENES_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<ImagenesAvance> selectByExample(ImagenesAvanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGENES_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    ImagenesAvance selectByPrimaryKey(Integer idImagenesAvance);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGENES_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") ImagenesAvance record, @Param("example") ImagenesAvanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGENES_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") ImagenesAvance record, @Param("example") ImagenesAvanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGENES_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(ImagenesAvance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMAGENES_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(ImagenesAvance record);
}