package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.MapaAvance;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.MapaAvanceExample;
import org.apache.ibatis.annotations.Param;

public interface MapaAvanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(MapaAvanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(MapaAvanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(Integer idMapaAvance);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(MapaAvance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(MapaAvance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<MapaAvance> selectByExample(MapaAvanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    MapaAvance selectByPrimaryKey(Integer idMapaAvance);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") MapaAvance record, @Param("example") MapaAvanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") MapaAvance record, @Param("example") MapaAvanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(MapaAvance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPA_AVANCE
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(MapaAvance record);
}