package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.Municipio;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.MunicipioExample;
import org.apache.ibatis.annotations.Param;

public interface MunicipioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(MunicipioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(MunicipioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(Integer idMunicipio);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(Municipio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(Municipio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<Municipio> selectByExample(MunicipioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    Municipio selectByPrimaryKey(Integer idMunicipio);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Municipio record, @Param("example") MunicipioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") Municipio record, @Param("example") MunicipioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(Municipio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(Municipio record);
}