package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.PartidaGenerica;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.PartidaGenericaExample;
import org.apache.ibatis.annotations.Param;

public interface PartidaGenericaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(PartidaGenericaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(PartidaGenericaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(Integer idPartida);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(PartidaGenerica record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(PartidaGenerica record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<PartidaGenerica> selectByExample(PartidaGenericaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    PartidaGenerica selectByPrimaryKey(Integer idPartida);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") PartidaGenerica record, @Param("example") PartidaGenericaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") PartidaGenerica record, @Param("example") PartidaGenericaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(PartidaGenerica record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTIDA_GENERICA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(PartidaGenerica record);
}