package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.ProgramaPartida;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.ProgramaPartidaExample;
import org.apache.ibatis.annotations.Param;

public interface ProgramaPartidaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(ProgramaPartidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(ProgramaPartidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(String idProgPartida);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(ProgramaPartida record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(ProgramaPartida record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<ProgramaPartida> selectByExample(ProgramaPartidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    ProgramaPartida selectByPrimaryKey(String idProgPartida);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") ProgramaPartida record, @Param("example") ProgramaPartidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") ProgramaPartida record, @Param("example") ProgramaPartidaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(ProgramaPartida record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PARTIDA
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(ProgramaPartida record);
}