package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.math.BigDecimal;
import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.ProgramaPres;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.ProgramaPresExample;
import org.apache.ibatis.annotations.Param;

public interface ProgramaPresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(ProgramaPresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(ProgramaPresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(BigDecimal idProgramaPres);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(ProgramaPres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(ProgramaPres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<ProgramaPres> selectByExample(ProgramaPresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    ProgramaPres selectByPrimaryKey(BigDecimal idProgramaPres);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") ProgramaPres record, @Param("example") ProgramaPresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") ProgramaPres record, @Param("example") ProgramaPresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(ProgramaPres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROGRAMA_PRES
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(ProgramaPres record);
}