package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.Ramo;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.RamoExample;
import org.apache.ibatis.annotations.Param;

public interface RamoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(RamoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(RamoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(Integer idRamo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(Ramo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(Ramo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<Ramo> selectByExample(RamoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    Ramo selectByPrimaryKey(Integer idRamo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Ramo record, @Param("example") RamoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") Ramo record, @Param("example") RamoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(Ramo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RAMO
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(Ramo record);
}