package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.TipoProyectoCat;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.TipoProyectoCatExample;
import org.apache.ibatis.annotations.Param;

public interface TipoProyectoCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPO_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(TipoProyectoCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPO_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(TipoProyectoCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPO_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(Integer idTipoProyecto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPO_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(TipoProyectoCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPO_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(TipoProyectoCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPO_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<TipoProyectoCat> selectByExample(TipoProyectoCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPO_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    TipoProyectoCat selectByPrimaryKey(Integer idTipoProyecto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPO_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") TipoProyectoCat record, @Param("example") TipoProyectoCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPO_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") TipoProyectoCat record, @Param("example") TipoProyectoCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPO_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(TipoProyectoCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPO_PROYECTO_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(TipoProyectoCat record);
}