package mx.gob.shcp.dgtsi.sfu.proyectos.repository;

import java.util.List;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.UnidadMedidaCat;
import mx.gob.shcp.dgtsi.sfu.proyectos.model.UnidadMedidaCatExample;
import org.apache.ibatis.annotations.Param;

public interface UnidadMedidaCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDAD_MEDIDA_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int countByExample(UnidadMedidaCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDAD_MEDIDA_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByExample(UnidadMedidaCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDAD_MEDIDA_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int deleteByPrimaryKey(Integer idUnidadMedida);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDAD_MEDIDA_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insert(UnidadMedidaCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDAD_MEDIDA_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int insertSelective(UnidadMedidaCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDAD_MEDIDA_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    List<UnidadMedidaCat> selectByExample(UnidadMedidaCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDAD_MEDIDA_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    UnidadMedidaCat selectByPrimaryKey(Integer idUnidadMedida);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDAD_MEDIDA_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExampleSelective(@Param("record") UnidadMedidaCat record, @Param("example") UnidadMedidaCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDAD_MEDIDA_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByExample(@Param("record") UnidadMedidaCat record, @Param("example") UnidadMedidaCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDAD_MEDIDA_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKeySelective(UnidadMedidaCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDAD_MEDIDA_CAT
     *
     * @mbggenerated Thu Jun 09 18:10:57 CDT 2016
     */
    int updateByPrimaryKey(UnidadMedidaCat record);
}